export const capizMunicipalities = {
  "Cuartero": ["Agcabugao", "Agdahon", "Agnaga", "Angub", "Balingasag", "Bito-on Ilawod", "Bito-on Ilaya", "Bun-od", "Carataya", "Lunayan", "Mahunodhunod", "Mahabang Sapa", "Maindang", "Mainit", "Malagab-i", "Nagba", "Poblacion Ilawod", "Poblacion Ilaya", "Poblacion Takas", "Puti-an", "San Antonio", "Sinabsaban"],
  "Dao": ["Aganan", "Agtambi", "Agtanguay", "Balucuan", "Bita", "Centro", "Daplas", "Duyoc", "Ilas Sur", "Lacaron", "Malonoy", "Manhoy", "Mapulang Bato", "Matagnop", "Nasunogan", "Poblacion Ilawod", "Poblacion Ilaya", "Quinabcaban", "Quinayuya", "San Agustin"],
  "Dumalag": ["Concepcion", "Consolacion", "Dolores", "Duran", "Poblacion", "San Agustin", "San Jose", "San Martin", "San Miguel", "San Rafael", "San Roque", "Santa Carmen", "Santa Cruz", "Santa Monica", "Santa Rita", "Santa Teresa", "Santo Angel", "Santo Niño", "Santo Rosario"],
  "Dumarao": ["Agbatuan", "Aglalana", "Aglanot", "Agsirab", "Alipasiawan", "Astorga", "Bayog", "Bungsuan", "Calapawan", "Codingle", "Cubi", "Dacuton", "Dangula", "Gibato", "Guinotos", "Jambad", "Janguslob", "Lawaan", "Malonoy", "Nagsulang", "Ongol Ilawod", "Ongol Ilaya", "Poblacion Ilawod", "Poblacion Ilaya", "Sagrada Familia", "Salcedo", "San Juan", "Sibariwan", "Tamulalod", "Taslan", "Tina", "Tinaytayan", "Traciano"],
  "Ivisan": ["Agmalobo", "Agustin Navarra", "Balaring", "Basiao", "Cabugao", "Cudian", "Ilaya-Ivisan", "Malocloc Norte", "Malocloc Sur", "Matnog", "Mianay", "Ondoy", "Poblacion Norte", "Poblacion Sur", "Santa Cruz"],
  "Jamindan": ["Agambulong", "Agbun-od", "Agcagay", "Aglibacao", "Agloloway", "Bayebaye", "Caridad", "Esperanza", "Fe", "Ganzon", "Guintas", "Igang", "Jaena Norte", "Jaena Sur", "Jagnaya", "Lapaz", "Linambasan", "Lucero", "Maantol", "Masgrau", "Milan", "Molet", "Pangabat", "Pangabuan", "Pasol-o", "Poblacion", "San Jose", "San Juan", "San Vicente", "Santo Rosario"],
  "Ma-Ayon": ["Aglimocon", "Alasaging", "Alayunan", "Balighot", "Batabat", "Bongbongan", "Cabungahan", "Canapian", "Carataya", "Duluan", "East Villaflores", "Fernandez", "Guinbi-alan", "Indayagan", "Jebaca", "Maalan", "Manayupit", "New Guia", "Quevedo", "Old Guia", "Palaguian", "Parallan", "Piña", "Poblacion Ilawod", "Poblacion Ilaya", "Poblacion Tabuc", "Quinabonglan", "Quinat-uyan", "Salgan", "Tapulang", "Tuburan", "West Villaflores"],
  "Mambusao": ["Atiplo", "Balat-an", "Balit", "Batiano", "Bating", "Bato Bato", "Baye", "Bergante", "Bunga", "Bula", "Bungsi", "Burias", "Caidquid", "Cala-agus", "Libo-o", "Manibad", "Maralag", "Najus-an", "Pangpang Norte", "Pangpang Sur", "Pinay", "Poblacion Proper", "Poblacion Tabuc", "Sinondojan", "Tugas", "Tumalalud"],
  "Panay": ["Agbalo", "Agbanban", "Agojo", "Anhawon", "Bagacay", "Bago Chiquito", "Bago Grande", "Bahit", "Bantique", "Bato", "Binangig", "Binantuan", "Bonga", "Buntod", "Butacal", "Cabugao Este", "Cabugao Oeste", "Calapawan", "Calitan", "Candual", "Cogon", "Daga", "Ilamnay", "Jamul-awon", "Lanipga", "Lat-Asan", "Libon", "Linao", "Linateran", "Lomboy", "Lus-Onan", "Magubilan", "Navitas", "Pawa", "Pili", "Poblacion Ilawod", "Poblacion Ilaya", "Poblacion Tabuc", "Talasa", "Tanza Norte", "Tanza Sur", "Tico"],
  "Panitan": ["Agbabadiang", "Agkilo", "Agloway", "Ambilay", "Bahit", "Balatucan", "Banga-an", "Cabugao", "Cabangahan", "Cadio", "Cala-an", "Capagao", "Cogon", "Conciencia", "Ensenagan", "Intampilan", "Pasugue", "Poblacion Ilawod", "Poblacion Ilaya", "Quios", "Salocon", "Tabuc Norte", "Tabuc Sur", "Timpas", "Tincupon", "Tinigban"],
  "Pilar": ["Balogo", "Binaobawan", "Blasco", "Casanayan", "Cayus", "Dayhagan", "Dulangan", "Monteflor", "Natividad", "Olalo", "Poblacion", "Rosario", "San Antonio", "San Blas", "San Esteban", "San Fernando", "San Nicolas", "San Pedro", "San Ramon", "San Silvestre", "Sinamongan", "Santa Fe", "Tabun-acan", "Yating"],
  "Pontevedra": ["Agbanog", "Agdalipe", "Ameligan", "Bailan", "Banate", "Bantigue", "Binuntucan", "Cabugao", "Gabuc", "Guba", "Hipona", "Ilawod", "Ilaya", "Intungcan", "Jolongajog", "Lantangan", "Linampongan", "Malag-it", "Manapao", "Rizal", "San Pedro", "Solo", "Sublangon", "Tabuc", "Tacas", "Yatingan"],
  "President Roxas": ["Aranguel", "Bayuyan", "Cabugcabug", "Cayus", "Culajao", "Dulunan", "Ibaca", "Madulano", "Maninang", "Marita", "Natividad", "Odiong", "Pandayan", "Poblacion", "Punta Cogon", "Quiajo", "Rizal", "Sangkal", "Santo Niño", "Tigbi", "Vizcaya"],
  "Roxas City": ["Adlawan", "Bago", "Balijuagan", "Banica", "Barra", "Bato", "Baybay", "Bolo", "Cabugao", "Cagay", "Cogon", "Culajao", "Culasi", "Dumolog", "Dayao", "Dinginan", "Gabu-an", "Inzo Arnaldo Village", "Jumaguicjic", "Lanot", "Lawa-an", "Libas", "Liong", "Loctugan", "Lonoy", "Milibili", "Mongpong", "Olotayan", "Poblacion I", "Poblacion II", "Poblacion III", "Poblacion IV", "Poblacion V", "Poblacion VI", "Poblacion VII", "Poblacion VIII", "Poblacion IX", "Poblacion X", "Poblacion XI", "Punta Cogon", "Punta Tabuc", "San Jose", "Sibaguan", "Talon", "Tanque", "Tanza", "Tiza"],
  "Sapi-an": ["Agsilab", "Agtatacay Norte", "Agtatacay Sur", "Bilao", "Damayan", "Dapdapan", "Lonoy", "Majanlud", "Maninang", "Poblacion"],
  "Sigma": ["Acuña", "Alipasiawan", "Amaga", "Balucuan", "Bangonbangon", "Capitan Ramon", "Cogon", "Daclan", "Duyuan", "Faraon", "Guinbaliwan", "Mianay", "Poblacion Norte", "Poblacion Sur", "Rizal", "Santa Elena", "Tawog", "Valentin"],
  "Tapaz": ["Abangay", "Acuña", "Agcococ", "Aglinab", "Aglupacan", "Agpalali", "Apero", "Artuz", "Bag-Ong Barrio", "Bato-bato", "Buri", "Camburanan", "Candelaria", "Carida", "Cristina", "Da-an Banwa", "Da-an Norte", "Da-an Sur", "Garcia", "Gebio-an", "Hilwan", "Initan", "Katipunan", "Lagdungan", "Lahug", "Libertad", "Mabini", "Maliao", "Malitbog", "Minan", "Nayawan", "Poblacion", "Rizal Norte", "Rizal Sur", "Roosevelt", "Roxas", "Salong", "San Antonio", "San Francisco", "San Jose", "San Julian", "San Miguel Ilawod", "San Miguel Ilaya", "San Nicolas", "San Pedro", "San Roque", "San Vicente", "Santa Ana", "Santa Petronila", "Senonod", "Siya", "Switch", "Tabon", "Tacayan", "Taft", "Taganghin", "Taslan", "Wright"]
};
