import { Submission, NotificationItem } from './db';

export const dummyBase64Pdf = "data:application/pdf;base64,JVBERi0xLjQKJcTl8uXrp/Og0MTGCjQgMCBvYmoKPDwgL0xlbmd0aCA1IDAgUiAvRmlsdGVyIC9GbGF0ZURlY29kZSA+PgpzdHJlYW0KeJzLSM3JyVcozy/KSVEEAELnBfUKZW5kc3RyZWFtCmVuZG9iago1IDAgb2JqCjE4CmVuZG9iagoxIDAgb2JqCjw8IC9UeXBlIC9DYXRhbG9nIC9QYWdlcyAyIDAgUiA+PgplbmRvYmoK";

export const dummyBase64Photo2x2 = "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='240' height='240' viewBox='0 0 240 240'><rect width='240' height='240' fill='%23e2e8f0'/><rect x='8' y='8' width='224' height='224' fill='%23003884' rx='6'/><circle cx='120' cy='90' r='42' fill='%23fde047'/><circle cx='120' cy='85' r='38' fill='%23cbd5e1'/><path d='M45 205 C 45 145, 195 145, 195 205 Z' fill='%23ffffff'/><rect x='16' y='195' width='208' height='25' fill='%230a192f' rx='4'/><text x='120' y='212' fill='%23ffffff' font-family='Arial, sans-serif' font-size='11' font-weight='bold' text-anchor='middle' letter-spacing='1'>CAPSU OFFICIAL 2x2 ID</text></svg>";

export const dummyBase64StudentId = "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='360' height='220' viewBox='0 0 360 220'><rect width='360' height='220' rx='12' fill='%23ffffff' stroke='%23003884' stroke-width='4'/><rect width='360' height='45' fill='%23003884' rx='10 10 0 0'/><text x='180' y='23' fill='%23ffffff' font-family='Arial, sans-serif' font-size='12' font-weight='bold' text-anchor='middle'>CAPIZ STATE UNIVERSITY</text><text x='180' y='37' fill='%23fbbf24' font-family='Arial, sans-serif' font-size='9' font-weight='bold' text-anchor='middle'>STUDENT IDENTIFICATION CARD</text><rect x='20' y='60' width='80' height='95' fill='%23e2e8f0' stroke='%2394a3b8' rx='6'/><circle cx='60' cy='95' r='20' fill='%2394a3b8'/><path d='M35 145 C 35 125, 85 125, 85 145 Z' fill='%2364748b'/><text x='115' y='80' fill='%23003884' font-family='Arial, sans-serif' font-size='13' font-weight='bold'>STUDENT IDENTITY</text><text x='115' y='100' fill='%23334155' font-family='Arial, sans-serif' font-size='10' font-weight='bold'>ID NO: 2024-CAPSU-0182</text><text x='115' y='118' fill='%23334155' font-family='Arial, sans-serif' font-size='10'>STATUS: ENROLLED REGULAR</text><text x='115' y='136' fill='%2316a34a' font-family='Arial, sans-serif' font-size='10' font-weight='bold'>VALID: ACADEMIC YEAR 2025-2026</text><rect x='20' y='168' width='320' height='34' fill='%23f1f5f9' rx='4'/><text x='180' y='190' fill='%230f172a' font-family='Courier, monospace' font-size='14' font-weight='bold' text-anchor='middle' letter-spacing='4'>|||| | ||||| || |||||| | |||</text></svg>";

export const dummyBase64Signature = "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='300' height='100' viewBox='0 0 300 100'><path d='M25 65 Q 45 10, 65 55 T 105 45 Q 125 15, 145 60 T 185 50 Q 215 10, 235 55 T 275 40' fill='none' stroke='%23003884' stroke-width='3' stroke-linecap='round'/><path d='M35 78 Q 145 88, 275 72' fill='none' stroke='%23003884' stroke-width='2' stroke-linecap='round'/></svg>";

export const dummyBase64RF = "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='600' height='850' viewBox='0 0 600 850'><rect width='600' height='850' fill='%23ffffff'/><rect x='15' y='15' width='570' height='820' fill='none' stroke='%23003884' stroke-width='2'/><rect x='18' y='18' width='564' height='814' fill='none' stroke='%23cbd5e1' stroke-width='1'/><rect x='20' y='20' width='560' height='80' fill='%23003884'/><text x='300' y='50' fill='%23ffffff' font-family='Arial, sans-serif' font-size='15' font-weight='bold' text-anchor='middle'>CAPIZ STATE UNIVERSITY</text><text x='300' y='68' fill='%23fbbf24' font-family='Arial, sans-serif' font-size='12' font-weight='bold' text-anchor='middle'>OFFICE OF THE UNIVERSITY REGISTRAR</text><text x='300' y='86' fill='%23ffffff' font-family='Arial, sans-serif' font-size='10' text-anchor='middle'>Roxas City Main Campus, Capiz, Philippines</text><rect x='120' y='115' width='360' height='30' rx='6' fill='%23eff6ff' stroke='%233b82f6'/><text x='300' y='135' fill='%231e3a8a' font-family='Arial, sans-serif' font-size='13' font-weight='bold' text-anchor='middle'>CERTIFICATE OF REGISTRATION (RF)</text><rect x='35' y='160' width='530' height='100' fill='%23f8fafc' stroke='%23cbd5e1' rx='4'/><text x='50' y='185' fill='%23475569' font-family='Arial, sans-serif' font-size='11' font-weight='bold'>STUDENT NAME:</text><text x='160' y='185' fill='%230f172a' font-family='Arial, sans-serif' font-size='11' font-weight='bold'>SANTOS, ANNA MARIE A.</text><text x='50' y='210' fill='%23475569' font-family='Arial, sans-serif' font-size='11' font-weight='bold'>STUDENT NO.:</text><text x='160' y='210' fill='%23003884' font-family='Arial, sans-serif' font-size='11' font-weight='bold'>2024-CAPSU-0182</text><text x='330' y='185' fill='%23475569' font-family='Arial, sans-serif' font-size='11' font-weight='bold'>COURSE / YEAR:</text><text x='435' y='185' fill='%230f172a' font-family='Arial, sans-serif' font-size='11' font-weight='bold'>BAEL - 2A</text><text x='330' y='210' fill='%23475569' font-family='Arial, sans-serif' font-size='11' font-weight='bold'>ACADEMIC YEAR:</text><text x='435' y='210' fill='%230f172a' font-family='Arial, sans-serif' font-size='11' font-weight='bold'>2025-2026 (1st Sem)</text><text x='50' y='235' fill='%23475569' font-family='Arial, sans-serif' font-size='11' font-weight='bold'>ENROLLMENT STATUS:</text><text x='180' y='235' fill='%2316a34a' font-family='Arial, sans-serif' font-size='11' font-weight='bold'>OFFICIALLY ENROLLED (REGULAR)</text><rect x='35' y='280' width='530' height='26' fill='%23003884'/><text x='50' y='297' fill='%23ffffff' font-family='Arial, sans-serif' font-size='10' font-weight='bold'>COURSE CODE</text><text x='160' y='297' fill='%23ffffff' font-family='Arial, sans-serif' font-size='10' font-weight='bold'>DESCRIPTIVE TITLE</text><text x='420' y='297' fill='%23ffffff' font-family='Arial, sans-serif' font-size='10' font-weight='bold'>UNITS</text><text x='490' y='297' fill='%23ffffff' font-family='Arial, sans-serif' font-size='10' font-weight='bold'>SECTION</text><rect x='35' y='306' width='530' height='26' fill='%23ffffff' stroke='%23f1f5f9'/><text x='50' y='323' fill='%231e293b' font-family='Arial, sans-serif' font-size='10' font-weight='bold'>ENG 201</text><text x='160' y='323' fill='%23334155' font-family='Arial, sans-serif' font-size='10'>Advanced English Grammar</text><text x='430' y='323' fill='%231e293b' font-family='Arial, sans-serif' font-size='10'>3.0</text><text x='500' y='323' fill='%231e293b' font-family='Arial, sans-serif' font-size='10'>BAEL 2A</text><rect x='35' y='332' width='530' height='26' fill='%23f8fafc' stroke='%23f1f5f9'/><text x='50' y='349' fill='%231e293b' font-family='Arial, sans-serif' font-size='10' font-weight='bold'>ENG 202</text><text x='160' y='349' fill='%23334155' font-family='Arial, sans-serif' font-size='10'>Introduction to Linguistics</text><text x='430' y='349' fill='%231e293b' font-family='Arial, sans-serif' font-size='10'>3.0</text><text x='500' y='349' fill='%231e293b' font-family='Arial, sans-serif' font-size='10'>BAEL 2A</text><rect x='35' y='358' width='530' height='26' fill='%23ffffff' stroke='%23f1f5f9'/><text x='50' y='375' fill='%231e293b' font-family='Arial, sans-serif' font-size='10' font-weight='bold'>LIT 101</text><text x='160' y='375' fill='%23334155' font-family='Arial, sans-serif' font-size='10'>Philippine Literature</text><text x='430' y='375' fill='%231e293b' font-family='Arial, sans-serif' font-size='10'>3.0</text><text x='500' y='375' fill='%231e293b' font-family='Arial, sans-serif' font-size='10'>BAEL 2A</text><rect x='35' y='384' width='530' height='26' fill='%23f8fafc' stroke='%23f1f5f9'/><text x='50' y='401' fill='%231e293b' font-family='Arial, sans-serif' font-size='10' font-weight='bold'>COMM 205</text><text x='160' y='401' fill='%23334155' font-family='Arial, sans-serif' font-size='10'>Speech &amp; Oral Communication</text><text x='430' y='401' fill='%231e293b' font-family='Arial, sans-serif' font-size='10'>3.0</text><text x='500' y='401' fill='%231e293b' font-family='Arial, sans-serif' font-size='10'>BAEL 2A</text><rect x='35' y='410' width='530' height='26' fill='%23ffffff' stroke='%23f1f5f9'/><text x='50' y='427' fill='%231e293b' font-family='Arial, sans-serif' font-size='10' font-weight='bold'>GE 104</text><text x='160' y='427' fill='%23334155' font-family='Arial, sans-serif' font-size='10'>Readings in Philippine History</text><text x='430' y='427' fill='%231e293b' font-family='Arial, sans-serif' font-size='10'>3.0</text><text x='500' y='427' fill='%231e293b' font-family='Arial, sans-serif' font-size='10'>BAEL 2A</text><rect x='35' y='436' width='530' height='26' fill='%23f8fafc' stroke='%23f1f5f9'/><text x='50' y='453' fill='%231e293b' font-family='Arial, sans-serif' font-size='10' font-weight='bold'>PE 3</text><text x='160' y='453' fill='%23334155' font-family='Arial, sans-serif' font-size='10'>Physical Education / Dance</text><text x='430' y='453' fill='%231e293b' font-family='Arial, sans-serif' font-size='10'>2.0</text><text x='500' y='453' fill='%231e293b' font-family='Arial, sans-serif' font-size='10'>BAEL 2A</text><rect x='35' y='462' width='530' height='26' fill='%23ffffff' stroke='%23f1f5f9'/><text x='50' y='479' fill='%231e293b' font-family='Arial, sans-serif' font-size='10' font-weight='bold'>NSTP 2</text><text x='160' y='479' fill='%23334155' font-family='Arial, sans-serif' font-size='10'>Civic Welfare Training Service 2</text><text x='430' y='479' fill='%231e293b' font-family='Arial, sans-serif' font-size='10'>3.0</text><text x='500' y='479' fill='%231e293b' font-family='Arial, sans-serif' font-size='10'>BAEL 2A</text><rect x='35' y='495' width='530' height='30' fill='%23eff6ff' stroke='%23bfdbfe'/><text x='50' y='515' fill='%231e3a8a' font-family='Arial, sans-serif' font-size='11' font-weight='bold'>TOTAL ACADEMIC UNITS ENROLLED:</text><text x='430' y='515' fill='%231e3a8a' font-family='Arial, sans-serif' font-size='12' font-weight='bold'>20.0 Units</text><g transform='translate(360, 560)'><circle cx='80' cy='60' r='55' fill='none' stroke='%23dc2626' stroke-width='2' stroke-dasharray='4,2'/><circle cx='80' cy='60' r='48' fill='none' stroke='%23dc2626' stroke-width='1'/><text x='80' y='48' fill='%23dc2626' font-family='Arial, sans-serif' font-size='8' font-weight='bold' text-anchor='middle'>CAPIZ STATE UNIVERSITY</text><text x='80' y='62' fill='%23dc2626' font-family='Arial, sans-serif' font-size='10' font-weight='bold' text-anchor='middle'>OFFICIALLY</text><text x='80' y='74' fill='%23dc2626' font-family='Arial, sans-serif' font-size='10' font-weight='bold' text-anchor='middle'>VALIDATED</text><text x='80' y='86' fill='%23dc2626' font-family='Arial, sans-serif' font-size='7' font-weight='bold' text-anchor='middle'>UNIVERSITY REGISTRAR</text></g><line x1='50' y1='640' x2='220' y2='640' stroke='%23334155' stroke-width='1'/><text x='135' y='655' fill='%23334155' font-family='Arial, sans-serif' font-size='10' font-weight='bold' text-anchor='middle'>Registrar In-Charge Signature</text><rect x='35' y='710' width='530' height='40' fill='%23f1f5f9' rx='4'/><text x='50' y='726' fill='%2364748b' font-family='Arial, sans-serif' font-size='9'>System Verification Hash: CAPSU-RF-2026-09281745-ENR</text><text x='50' y='740' fill='%2364748b' font-family='Arial, sans-serif' font-size='9'>This document serves as the official Registration Form for scholarship compliance.</text></svg>";

export const dummyBase64GWA = "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='600' height='850' viewBox='0 0 600 850'><rect width='600' height='850' fill='%23ffffff'/><rect x='15' y='15' width='570' height='820' fill='none' stroke='%23003884' stroke-width='2'/><rect x='18' y='18' width='564' height='814' fill='none' stroke='%23cbd5e1' stroke-width='1'/><rect x='20' y='20' width='560' height='80' fill='%23003884'/><text x='300' y='50' fill='%23ffffff' font-family='Arial, sans-serif' font-size='15' font-weight='bold' text-anchor='middle'>CAPIZ STATE UNIVERSITY</text><text x='300' y='68' fill='%23fbbf24' font-family='Arial, sans-serif' font-size='12' font-weight='bold' text-anchor='middle'>OFFICIAL REPORT OF GRADES &amp; GWA</text><text x='300' y='86' fill='%23ffffff' font-family='Arial, sans-serif' font-size='10' text-anchor='middle'>Guidance Office &amp; Scholarship Evaluation Section</text><rect x='100' y='115' width='400' height='30' rx='6' fill='%23f0fdf4' stroke='%2322c55e'/><text x='300' y='135' fill='%2315803d' font-family='Arial, sans-serif' font-size='13' font-weight='bold' text-anchor='middle'>GENERAL WEIGHTED AVERAGE (GWA) CERTIFICATION</text><rect x='35' y='160' width='530' height='100' fill='%23f8fafc' stroke='%23cbd5e1' rx='4'/><text x='50' y='185' fill='%23475569' font-family='Arial, sans-serif' font-size='11' font-weight='bold'>APPLICANT NAME:</text><text x='170' y='185' fill='%230f172a' font-family='Arial, sans-serif' font-size='11' font-weight='bold'>SANTOS, ANNA MARIE A.</text><text x='50' y='210' fill='%23475569' font-family='Arial, sans-serif' font-size='11' font-weight='bold'>STUDENT NO.:</text><text x='170' y='210' fill='%23003884' font-family='Arial, sans-serif' font-size='11' font-weight='bold'>2024-CAPSU-0182</text><text x='330' y='185' fill='%23475569' font-family='Arial, sans-serif' font-size='11' font-weight='bold'>DEGREE PROGRAM:</text><text x='445' y='185' fill='%230f172a' font-family='Arial, sans-serif' font-size='11' font-weight='bold'>BAEL - 2A</text><text x='330' y='210' fill='%23475569' font-family='Arial, sans-serif' font-size='11' font-weight='bold'>EVALUATION PERIOD:</text><text x='445' y='210' fill='%230f172a' font-family='Arial, sans-serif' font-size='11' font-weight='bold'>1st Sem 2025-2026</text><text x='50' y='235' fill='%23475569' font-family='Arial, sans-serif' font-size='11' font-weight='bold'>SCHOLARSHIP STANDING:</text><text x='205' y='235' fill='%2316a34a' font-family='Arial, sans-serif' font-size='11' font-weight='bold'>EXCELLENT (ACADEMIC QUALIFIER)</text><rect x='35' y='280' width='530' height='26' fill='%23003884'/><text x='50' y='297' fill='%23ffffff' font-family='Arial, sans-serif' font-size='10' font-weight='bold'>COURSE CODE</text><text x='160' y='297' fill='%23ffffff' font-family='Arial, sans-serif' font-size='10' font-weight='bold'>COURSE TITLE</text><text x='380' y='297' fill='%23ffffff' font-family='Arial, sans-serif' font-size='10' font-weight='bold'>UNITS</text><text x='440' y='297' fill='%23ffffff' font-family='Arial, sans-serif' font-size='10' font-weight='bold'>FINAL GRADE</text><text x='515' y='297' fill='%23ffffff' font-family='Arial, sans-serif' font-size='10' font-weight='bold'>REMARKS</text><rect x='35' y='306' width='530' height='26' fill='%23ffffff' stroke='%23f1f5f9'/><text x='50' y='323' fill='%231e293b' font-family='Arial, sans-serif' font-size='10' font-weight='bold'>ENG 201</text><text x='160' y='323' fill='%23334155' font-family='Arial, sans-serif' font-size='10'>Advanced English Grammar</text><text x='390' y='323' fill='%231e293b' font-family='Arial, sans-serif' font-size='10'>3.0</text><text x='460' y='323' fill='%2316a34a' font-family='Arial, sans-serif' font-size='10' font-weight='bold'>1.25</text><text x='515' y='323' fill='%2316a34a' font-family='Arial, sans-serif' font-size='10'>Passed</text><rect x='35' y='332' width='530' height='26' fill='%23f8fafc' stroke='%23f1f5f9'/><text x='50' y='349' fill='%231e293b' font-family='Arial, sans-serif' font-size='10' font-weight='bold'>ENG 202</text><text x='160' y='349' fill='%23334155' font-family='Arial, sans-serif' font-size='10'>Introduction to Linguistics</text><text x='390' y='349' fill='%231e293b' font-family='Arial, sans-serif' font-size='10'>3.0</text><text x='460' y='349' fill='%2316a34a' font-family='Arial, sans-serif' font-size='10' font-weight='bold'>1.50</text><text x='515' y='349' fill='%2316a34a' font-family='Arial, sans-serif' font-size='10'>Passed</text><rect x='35' y='358' width='530' height='26' fill='%23ffffff' stroke='%23f1f5f9'/><text x='50' y='375' fill='%231e293b' font-family='Arial, sans-serif' font-size='10' font-weight='bold'>LIT 101</text><text x='160' y='375' fill='%23334155' font-family='Arial, sans-serif' font-size='10'>Philippine Literature</text><text x='390' y='375' fill='%231e293b' font-family='Arial, sans-serif' font-size='10'>3.0</text><text x='460' y='375' fill='%2316a34a' font-family='Arial, sans-serif' font-size='10' font-weight='bold'>1.25</text><text x='515' y='375' fill='%2316a34a' font-family='Arial, sans-serif' font-size='10'>Passed</text><rect x='35' y='384' width='530' height='26' fill='%23f8fafc' stroke='%23f1f5f9'/><text x='50' y='401' fill='%231e293b' font-family='Arial, sans-serif' font-size='10' font-weight='bold'>COMM 205</text><text x='160' y='401' fill='%23334155' font-family='Arial, sans-serif' font-size='10'>Speech &amp; Oral Communication</text><text x='390' y='401' fill='%231e293b' font-family='Arial, sans-serif' font-size='10'>3.0</text><text x='460' y='401' fill='%2316a34a' font-family='Arial, sans-serif' font-size='10' font-weight='bold'>1.25</text><text x='515' y='401' fill='%2316a34a' font-family='Arial, sans-serif' font-size='10'>Passed</text><rect x='35' y='410' width='530' height='26' fill='%23ffffff' stroke='%23f1f5f9'/><text x='50' y='427' fill='%231e293b' font-family='Arial, sans-serif' font-size='10' font-weight='bold'>GE 104</text><text x='160' y='427' fill='%23334155' font-family='Arial, sans-serif' font-size='10'>Readings in Philippine History</text><text x='390' y='427' fill='%231e293b' font-family='Arial, sans-serif' font-size='10'>3.0</text><text x='460' y='427' fill='%2316a34a' font-family='Arial, sans-serif' font-size='10' font-weight='bold'>1.50</text><text x='515' y='427' fill='%2316a34a' font-family='Arial, sans-serif' font-size='10'>Passed</text><rect x='35' y='436' width='530' height='26' fill='%23f8fafc' stroke='%23f1f5f9'/><text x='50' y='453' fill='%231e293b' font-family='Arial, sans-serif' font-size='10' font-weight='bold'>PE 3</text><text x='160' y='453' fill='%23334155' font-family='Arial, sans-serif' font-size='10'>Physical Education / Dance</text><text x='390' y='453' fill='%231e293b' font-family='Arial, sans-serif' font-size='10'>2.0</text><text x='460' y='453' fill='%2316a34a' font-family='Arial, sans-serif' font-size='10' font-weight='bold'>1.00</text><text x='515' y='453' fill='%2316a34a' font-family='Arial, sans-serif' font-size='10'>Passed</text><rect x='35' y='480' width='530' height='60' rx='8' fill='%23ecfdf5' stroke='%2310b981' stroke-width='2'/><text x='50' y='505' fill='%23065f46' font-family='Arial, sans-serif' font-size='11' font-weight='bold'>COMPUTED GENERAL WEIGHTED AVERAGE (GWA):</text><text x='50' y='525' fill='%23047857' font-family='Arial, sans-serif' font-size='10'>Total Academic Units Credited: 20.0 Units</text><rect x='420' y='488' width='130' height='44' rx='6' fill='%2310b981'/><text x='485' y='518' fill='%23ffffff' font-family='Arial, sans-serif' font-size='22' font-weight='bold' text-anchor='middle'>1.35</text><g transform='translate(360, 570)'><circle cx='80' cy='60' r='55' fill='none' stroke='%23003884' stroke-width='2' stroke-dasharray='4,2'/><circle cx='80' cy='60' r='48' fill='none' stroke='%23003884' stroke-width='1'/><text x='80' y='48' fill='%23003884' font-family='Arial, sans-serif' font-size='8' font-weight='bold' text-anchor='middle'>CAPIZ STATE UNIVERSITY</text><text x='80' y='62' fill='%23003884' font-family='Arial, sans-serif' font-size='9' font-weight='bold' text-anchor='middle'>ACADEMIC RECORD</text><text x='80' y='74' fill='%23003884' font-family='Arial, sans-serif' font-size='10' font-weight='bold' text-anchor='middle'>VERIFIED</text><text x='80' y='86' fill='%23003884' font-family='Arial, sans-serif' font-size='7' font-weight='bold' text-anchor='middle'>DEAN OF INSTRUCTION</text></g><line x1='50' y1='650' x2='220' y2='650' stroke='%23334155' stroke-width='1'/><text x='135' y='665' fill='%23334155' font-family='Arial, sans-serif' font-size='10' font-weight='bold' text-anchor='middle'>College Dean Signature</text><rect x='35' y='720' width='530' height='40' fill='%23f1f5f9' rx='4'/><text x='50' y='736' fill='%2364748b' font-family='Arial, sans-serif' font-size='9'>Certification Code: CAPSU-GWA-2026-09281745-HONORS</text><text x='50' y='750' fill='%2364748b' font-family='Arial, sans-serif' font-size='9'>Official document for Guidance &amp; Counseling Scholarship Verification.</text></svg>";

const dummyBase64Image = dummyBase64Photo2x2;

export const defaultSubmissions: Submission[] = [
  {
    id: 'sub-seed-1',
    studentId: '2024-CAPSU-0182',
    studentName: 'Anna Marie A. Santos',
    scholarshipType: 'Externally-Funded (Pag-ulikid)',
    status: 'Complete',
    submittedAt: '2026-03-11T10:00:00Z',
    data: {
      studentId: '2024-CAPSU-0182',
      familyName: 'Santos',
      firstName: 'Anna Marie',
      middleName: 'A.',
      course: 'BAEL',
      courseFull: 'Bachelor of Arts in English Language',
      yearLevel: 'Second year',
      section: 'BAEL 2A',
      sex: 'Female',
      civilStatus: 'Single',
      scholarshipType: 'Externally-Funded (Pag-ulikid)',
      scholarshipCategory: 'Pag-ulikid',
      fundingType: 'Externally-Funded',
      academicYear: 'A.Y. 2025-2026 - 2nd Semester',
      status: 'Complete',
      submittedAt: '2026-03-11T10:00:00Z',
      fatherName: 'Roberto Santos',
      fatherOccupation: 'Farmer',
      motherName: 'Elena Santos',
      motherOccupation: 'Housewife',
      guardianOccupation: 'None',
      parentsEducationalAttainment: 'High school Graduate',
      monthlyIncome: 'below Php10,000',
      firstGenCollege: 'Yes',
      livingWith: 'Parents/Guardians',
      housingType: 'Own house',
      accessResources: ['Study space', 'Textbooks and learning materials'],
      workingStudent: 'No',
      classifications: ['Low income family/ Economically disadvantaged student', 'First Generation student (Parents did not complete a college degree)'],
      photo2x2: dummyBase64Photo2x2,
      studentIdCard: dummyBase64StudentId,
      signature: dummyBase64Signature,
      signedAt: '2026-03-11T10:00:00Z',
      requirements: [
        { name: '2x2 Recent Formal ID Photo', status: 'Verified' },
        { name: 'Valid Student ID', status: 'Verified' },
        { name: 'Certificate of Grades (COG)', status: 'Verified' },
        { name: 'Certificate of Registration (COR)', status: 'Verified' },
        { name: 'Proof of Income / Certificate of Indigency', status: 'Verified' },
        { name: 'Certificate of Good Moral Character', status: 'Verified' }
      ]
    },
    files: [
      { id: 'f-photo', name: 'Santos_2x2_ID_Photo.png', category: '2x2 Recent Formal ID Photo', type: 'image/svg+xml', size: '320 KB', data: dummyBase64Photo2x2, verified: true, status: 'Verified' },
      { id: 'f-id', name: 'Santos_Valid_Student_ID.png', category: 'Valid Student ID', type: 'image/svg+xml', size: '450 KB', data: dummyBase64StudentId, verified: true, status: 'Verified' },
      { id: 'f-1', name: 'Santos_General_Weighted_Average_GWA.png', category: 'GWA', type: 'image/svg+xml', size: '152 KB', data: dummyBase64GWA, verified: true, status: 'Verified' },
      { id: 'f-2', name: 'Santos_Registration_Form_RF.png', category: 'RF', type: 'image/svg+xml', size: '145 KB', data: dummyBase64RF, verified: true, status: 'Verified' },
      { id: 'f-2nd-rf', name: 'Santos_Registration_Form_2ndSem_RF.png', category: 'RF_2', type: 'image/svg+xml', size: '145 KB', data: dummyBase64RF, verified: true, status: 'Verified' },
      { id: 'f-2nd-gwa', name: 'Santos_GWA_2ndSem.png', category: 'GWA_2', type: 'image/svg+xml', size: '152 KB', data: dummyBase64GWA, verified: true, status: 'Verified' },
      { id: 'f-3', name: 'Santos_Certificate_of_Indigency.pdf', category: 'Proof of Income / Certificate of Indigency', type: 'application/pdf', size: '620 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-4', name: 'Santos_Good_Moral_Character.pdf', category: 'Certificate of Good Moral Character', type: 'application/pdf', size: '540 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' }
    ]
  },
  {
    id: 'sub-seed-2',
    studentId: '2024-CAPSU-0195',
    studentName: 'Patricia Jane K. Manalo',
    scholarshipType: 'Externally-Funded (CHED - Tulong Dunong)',
    status: 'Incomplete',
    submittedAt: '2026-03-11T09:30:00Z',
    data: {
      studentId: '2024-CAPSU-0195',
      familyName: 'Manalo',
      firstName: 'Patricia Jane',
      middleName: 'K.',
      course: 'BAEL',
      courseFull: 'Bachelor of Arts in English Language',
      yearLevel: 'Second year',
      section: 'BAEL 2A',
      sex: 'Female',
      civilStatus: 'Single',
      scholarshipType: 'Externally-Funded (CHED - Tulong Dunong)',
      scholarshipCategory: 'Tulong Dunong',
      fundingType: 'Externally-Funded',
      academicYear: 'A.Y. 2025-2026 - 2nd Semester',
      status: 'Incomplete',
      submittedAt: '2026-03-11T09:30:00Z',
      fatherName: 'Ricardo Manalo',
      fatherOccupation: 'Fisherman',
      motherName: 'Carmen Manalo',
      motherOccupation: 'Vendor',
      guardianOccupation: 'None',
      parentsEducationalAttainment: 'Elementary Graduate',
      monthlyIncome: 'below Php10,000',
      firstGenCollege: 'Yes',
      livingWith: 'Parents/Guardians',
      housingType: 'Own house',
      accessResources: ['Study space'],
      workingStudent: 'Yes, part-time',
      workingStudentTypeOfWork: 'Store Assistant on weekends',
      classifications: ['Low income family/ Economically disadvantaged student', 'Working Student'],
      requirements: [
        { name: 'Certificate of Grades (COG)', status: 'Verified' },
        { name: 'Certificate of Registration (COR)', status: 'Verified' },
        { name: '2x2 Recent Formal ID Photo', status: 'Verified' },
        { name: 'Proof of Income / Certificate of Indigency', status: 'Pending' }
      ]
    },
    files: [
      { id: 'f-6', name: 'Manalo_General_Weighted_Average_GWA.png', category: 'GWA', type: 'image/svg+xml', size: '152 KB', data: dummyBase64GWA, verified: true, status: 'Verified' },
      { id: 'f-7', name: 'Manalo_Registration_Form_RF.png', category: 'RF', type: 'image/svg+xml', size: '145 KB', data: dummyBase64RF, verified: true, status: 'Verified' },
      { id: 'f-8', name: 'Manalo_2x2_ID_Photo.png', category: '2x2 Recent Formal ID Photo', type: 'image/svg+xml', size: '310 KB', data: dummyBase64Image, verified: true, status: 'Verified' }
    ]
  },
  {
    id: 'sub-seed-3',
    studentId: '2022-CAPSU-0041',
    studentName: 'Damian James O. Emilio',
    scholarshipType: 'Externally-Funded (CHED - ANAC-IP)',
    status: 'Incomplete',
    submittedAt: '2026-03-11T08:15:00Z',
    data: {
      studentId: '2022-CAPSU-0041',
      familyName: 'Emilio',
      firstName: 'Damian James',
      middleName: 'O.',
      course: 'BSFT',
      courseFull: 'Bachelor of Science in Food Technology',
      yearLevel: 'Fourth year',
      section: 'BSFT 4A',
      sex: 'Male',
      civilStatus: 'Single',
      scholarshipType: 'Externally-Funded (CHED - ANAC-IP)',
      scholarshipCategory: 'ANAC - IP',
      fundingType: 'Externally-Funded',
      academicYear: 'A.Y. 2025-2026 - 2nd Semester',
      status: 'Incomplete',
      submittedAt: '2026-03-11T08:15:00Z',
      fatherName: 'Nestor Emilio',
      fatherOccupation: 'Indigenous Artisan / Farmer',
      motherName: 'Leonora Emilio',
      motherOccupation: 'Weaver',
      guardianOccupation: 'None',
      parentsEducationalAttainment: 'Elementary Level',
      monthlyIncome: 'below Php10,000',
      firstGenCollege: 'Yes',
      livingWith: 'Boarding house',
      housingType: 'Boarding house',
      accessResources: ['Study space'],
      workingStudent: 'No',
      classifications: ['Indigenous Peoples (IPs)', 'From geographically isolated & disadvantaged area (GIDA)'],
      requirements: [
        { name: 'Certificate of Grades (COG)', status: 'Verified' },
        { name: 'Certificate of Registration (COR)', status: 'Verified' },
        { name: 'Proof of Income / Certificate of Indigency', status: 'Pending' }
      ]
    },
    files: [
      { id: 'f-9', name: 'Emilio_General_Weighted_Average_GWA.png', category: 'GWA', type: 'image/svg+xml', size: '152 KB', data: dummyBase64GWA, verified: true, status: 'Verified' },
      { id: 'f-10', name: 'Emilio_Registration_Form_RF.png', category: 'RF', type: 'image/svg+xml', size: '145 KB', data: dummyBase64RF, verified: true, status: 'Verified' },
      { id: 'f-11', name: 'Emilio_NCIP_Certificate.pdf', category: 'Proof of Income / Certificate of Indigency', type: 'application/pdf', size: '1.8 MB', data: dummyBase64Pdf, verified: false, status: 'Pending', remarks: 'NCIP seal validation in progress' }
    ]
  },
  {
    id: 'sub-seed-4',
    studentId: '2022-CAPSU-0089',
    studentName: 'Paul John N. Dela Cruz',
    scholarshipType: 'Internally-Funded (President - FLP)',
    status: 'Incomplete',
    submittedAt: '2026-03-11T07:45:00Z',
    data: {
      studentId: '2022-CAPSU-0089',
      familyName: 'Dela Cruz',
      firstName: 'Paul John',
      middleName: 'N.',
      course: 'BSOA',
      courseFull: 'Bachelor of Science in Office Administration',
      yearLevel: 'Fourth year',
      section: 'BSOA 4A',
      sex: 'Male',
      civilStatus: 'Single',
      scholarshipType: 'Internally-Funded (President - FLP)',
      scholarshipCategory: 'President - FLP',
      fundingType: 'Internally-Funded',
      academicYear: 'A.Y. 2025-2026 - 2nd Semester',
      status: 'Incomplete',
      submittedAt: '2026-03-11T07:45:00Z',
      fatherName: 'Federico Dela Cruz',
      fatherOccupation: 'Tricycle Driver',
      motherName: 'Maria Dela Cruz',
      motherOccupation: 'Sari-sari Store Owner',
      guardianOccupation: 'None',
      parentsEducationalAttainment: 'High School Level',
      monthlyIncome: 'Php10,001 - 20,000',
      firstGenCollege: 'Yes',
      livingWith: 'Parents/Guardians',
      housingType: 'Own house',
      accessResources: ['Personal Computer/Laptop', 'Internet Connection', 'Study space'],
      workingStudent: 'No',
      classifications: ['Regular student (I do not belong to any of this group classification)'],
      requirements: [
        { name: 'Certificate of Grades (COG)', status: 'Verified' },
        { name: 'Certificate of Registration (COR)', status: 'Verified' }
      ]
    },
    files: [
      { id: 'f-12', name: 'DelaCruz_GWA_Report.png', category: 'GWA', type: 'image/svg+xml', size: '152 KB', data: dummyBase64GWA, verified: true, status: 'Verified' },
      { id: 'f-13', name: 'DelaCruz_RF_Document.png', category: 'RF', type: 'image/svg+xml', size: '145 KB', data: dummyBase64RF, verified: true, status: 'Verified' }
    ]
  },
  {
    id: 'sub-seed-5',
    studentId: '2023-CAPSU-0312',
    studentName: 'Charlotte Alexis N. Tuvera',
    scholarshipType: 'Internally-Funded (Valedictorian)',
    status: 'Incomplete',
    submittedAt: '2026-03-10T14:20:00Z',
    data: {
      studentId: '2023-CAPSU-0312',
      familyName: 'Tuvera',
      firstName: 'Charlotte Alexis',
      middleName: 'N.',
      course: 'BSCS',
      courseFull: 'Bachelor of Science in Computer Science',
      yearLevel: 'Third year',
      section: 'BSCS 3A',
      sex: 'Female',
      civilStatus: 'Single',
      scholarshipType: 'Internally-Funded (Valedictorian)',
      scholarshipCategory: 'Valedictorian',
      fundingType: 'Internally-Funded',
      academicYear: 'A.Y. 2025-2026 - 2nd Semester',
      status: 'Incomplete',
      submittedAt: '2026-03-10T14:20:00Z',
      fatherName: 'Alexander Tuvera',
      fatherOccupation: 'Mechanic',
      motherName: 'Corazon Tuvera',
      motherOccupation: 'Seamstress',
      guardianOccupation: 'None',
      parentsEducationalAttainment: 'High school Graduate',
      monthlyIncome: 'Php10,001 - 20,000',
      firstGenCollege: 'No',
      livingWith: 'Parents/Guardians',
      housingType: 'Own house',
      accessResources: ['Personal Computer/Laptop', 'Internet Connection', 'Study space', 'Textbooks and learning materials'],
      workingStudent: 'No',
      classifications: ['Regular student (I do not belong to any of this group classification)'],
      requirements: [
        { name: 'Certificate of Grades (COG)', status: 'Verified' },
        { name: 'Certificate of Registration (COR)', status: 'Verified' }
      ]
    },
    files: [
      { id: 'f-14', name: 'Tuvera_Academic_COG.pdf', category: 'Certificate of Grades (COG)', type: 'application/pdf', size: '1.3 MB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-15', name: 'Tuvera_COR_Current.pdf', category: 'Certificate of Registration (COR)', type: 'application/pdf', size: '910 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' }
    ]
  },
  {
    id: 'sub-seed-6',
    studentId: '2023-CAPSU-0205',
    studentName: 'Michael G. Burata',
    scholarshipType: 'Internally-Funded (Academic Full)',
    status: 'Complete',
    submittedAt: '2026-03-10T11:00:00Z',
    data: {
      studentId: '2023-CAPSU-0205',
      familyName: 'Burata',
      firstName: 'Michael',
      middleName: 'G.',
      course: 'BSCS',
      courseFull: 'Bachelor of Science in Computer Science',
      yearLevel: 'Third year',
      section: 'BSCS 3A',
      sex: 'Male',
      civilStatus: 'Single',
      scholarshipType: 'Internally-Funded (Academic Full)',
      scholarshipCategory: 'Full',
      fundingType: 'Internally-Funded',
      academicYear: 'A.Y. 2025-2026 - 2nd Semester',
      status: 'Complete',
      submittedAt: '2026-03-10T11:00:00Z',
      fatherName: 'Gregorio Burata',
      fatherOccupation: 'Carpenter',
      motherName: 'Teresa Burata',
      motherOccupation: 'Barangay Health Worker',
      guardianOccupation: 'None',
      parentsEducationalAttainment: 'High school Graduate',
      monthlyIncome: 'below Php10,000',
      firstGenCollege: 'Yes',
      livingWith: 'Parents/Guardians',
      housingType: 'Own house',
      accessResources: ['Personal Computer/Laptop', 'Internet Connection', 'Study space'],
      workingStudent: 'No',
      classifications: ['Low income family/ Economically disadvantaged student'],
      requirements: [
        { name: 'Certificate of Grades (COG)', status: 'Verified' },
        { name: 'Certificate of Registration (COR)', status: 'Verified' },
        { name: 'Proof of Income / Certificate of Indigency', status: 'Verified' },
        { name: 'Certificate of Good Moral Character', status: 'Verified' }
      ]
    },
    files: [
      { id: 'f-16', name: 'Burata_COG_GWA125.pdf', category: 'Certificate of Grades (COG)', type: 'application/pdf', size: '1.6 MB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-17', name: 'Burata_COR_Official.pdf', category: 'Certificate of Registration (COR)', type: 'application/pdf', size: '840 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-18', name: 'Burata_Indigency.pdf', category: 'Proof of Income / Certificate of Indigency', type: 'application/pdf', size: '590 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-19', name: 'Burata_GoodMoral.pdf', category: 'Certificate of Good Moral Character', type: 'application/pdf', size: '510 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' }
    ]
  },
  {
    id: 'sub-seed-7',
    studentId: '2023-CAPSU-0118',
    studentName: 'Chery Joy M. Marcelino',
    scholarshipType: 'Externally-Funded (CHED - Tulong Dunong)',
    status: 'Complete',
    submittedAt: '2026-03-10T09:10:00Z',
    data: {
      studentId: '2023-CAPSU-0118',
      familyName: 'Marcelino',
      firstName: 'Chery Joy',
      middleName: 'M.',
      course: 'BSCS',
      courseFull: 'Bachelor of Science in Computer Science',
      yearLevel: 'Third year',
      section: 'BSCS 3A',
      sex: 'Female',
      civilStatus: 'Single',
      scholarshipType: 'Externally-Funded (CHED - Tulong Dunong)',
      scholarshipCategory: 'Tulong Dunong',
      fundingType: 'Externally-Funded',
      academicYear: 'A.Y. 2025-2026 - 2nd Semester',
      status: 'Complete',
      submittedAt: '2026-03-10T09:10:00Z',
      fatherName: 'Manuel Marcelino',
      fatherOccupation: 'Security Guard',
      motherName: 'Joy Marcelino',
      motherOccupation: 'Housewife',
      guardianOccupation: 'None',
      parentsEducationalAttainment: 'High school Graduate',
      monthlyIncome: 'below Php10,000',
      firstGenCollege: 'Yes',
      livingWith: 'Parents/Guardians',
      housingType: 'Own house',
      accessResources: ['Personal Computer/Laptop', 'Study space'],
      workingStudent: 'No',
      classifications: ['Low income family/ Economically disadvantaged student', 'First Generation student (Parents did not complete a college degree)'],
      requirements: [
        { name: 'Certificate of Grades (COG)', status: 'Verified' },
        { name: 'Certificate of Registration (COR)', status: 'Verified' },
        { name: 'Proof of Income / Certificate of Indigency', status: 'Verified' }
      ]
    },
    files: [
      { id: 'f-20', name: 'Marcelino_COG.pdf', category: 'Certificate of Grades (COG)', type: 'application/pdf', size: '1.2 MB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-21', name: 'Marcelino_COR.pdf', category: 'Certificate of Registration (COR)', type: 'application/pdf', size: '820 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-22', name: 'Marcelino_Indigency.pdf', category: 'Proof of Income / Certificate of Indigency', type: 'application/pdf', size: '610 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' }
    ]
  },
  {
    id: 'sub-seed-8',
    studentId: '2024-CAPSU-0044',
    studentName: 'Jessica Mae E. Dela Cruz',
    scholarshipType: 'Internally-Funded (Academic Partial)',
    status: 'Complete',
    submittedAt: '2026-03-09T16:00:00Z',
    data: {
      studentId: '2024-CAPSU-0044',
      familyName: 'Dela Cruz',
      firstName: 'Jessica Mae',
      middleName: 'E.',
      course: 'BSCS',
      courseFull: 'Bachelor of Science in Computer Science',
      yearLevel: 'Second year',
      section: 'BSCS 2A',
      sex: 'Female',
      civilStatus: 'Single',
      scholarshipType: 'Internally-Funded (Academic Partial)',
      scholarshipCategory: 'Partial',
      fundingType: 'Internally-Funded',
      academicYear: 'A.Y. 2025-2026 - 2nd Semester',
      status: 'Complete',
      submittedAt: '2026-03-09T16:00:00Z',
      fatherName: 'Eduardo Dela Cruz',
      fatherOccupation: 'Electrician',
      motherName: 'Milagros Dela Cruz',
      motherOccupation: 'Dressmaker',
      guardianOccupation: 'None',
      parentsEducationalAttainment: 'College Level',
      monthlyIncome: 'Php10,001 - 20,000',
      firstGenCollege: 'No',
      livingWith: 'Parents/Guardians',
      housingType: 'Own house',
      accessResources: ['Personal Computer/Laptop', 'Internet Connection', 'Study space'],
      workingStudent: 'No',
      classifications: ['Regular student (I do not belong to any of this group classification)'],
      requirements: [
        { name: 'Certificate of Grades (COG)', status: 'Verified' },
        { name: 'Certificate of Registration (COR)', status: 'Verified' },
        { name: 'Certificate of Good Moral Character', status: 'Verified' }
      ]
    },
    files: [
      { id: 'f-23', name: 'Jessica_COG_Official.pdf', category: 'Certificate of Grades (COG)', type: 'application/pdf', size: '1.3 MB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-24', name: 'Jessica_COR_Form.pdf', category: 'Certificate of Registration (COR)', type: 'application/pdf', size: '890 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-25', name: 'Jessica_Moral.pdf', category: 'Certificate of Good Moral Character', type: 'application/pdf', size: '540 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' }
    ]
  },
  {
    id: 'sub-seed-9',
    studentId: '2025-CAPSU-0112',
    studentName: 'Mark Josh P. Lorenzo',
    scholarshipType: 'Externally-Funded (Tertiary Education Subsidy - TES)',
    status: 'Complete',
    submittedAt: '2026-03-09T14:30:00Z',
    data: {
      studentId: '2025-CAPSU-0112',
      familyName: 'Lorenzo',
      firstName: 'Mark Josh',
      middleName: 'P.',
      course: 'BSOA',
      courseFull: 'Bachelor of Science in Office Administration',
      yearLevel: 'First year',
      section: 'BSOA 1A',
      sex: 'Male',
      civilStatus: 'Single',
      scholarshipType: 'Externally-Funded (Tertiary Education Subsidy - TES)',
      scholarshipCategory: 'TES',
      fundingType: 'Externally-Funded',
      academicYear: 'A.Y. 2025-2026 - 2nd Semester',
      status: 'Complete',
      submittedAt: '2026-03-09T14:30:00Z',
      fatherName: 'Jose Lorenzo',
      fatherOccupation: 'Farmer',
      motherName: 'Lina Lorenzo',
      motherOccupation: 'Housewife',
      guardianOccupation: 'None',
      parentsEducationalAttainment: 'High School Level',
      monthlyIncome: 'below Php10,000',
      firstGenCollege: 'Yes',
      livingWith: 'Parents/Guardians',
      housingType: 'Own house',
      accessResources: ['Study space'],
      workingStudent: 'No',
      classifications: ['Low income family/ Economically disadvantaged student', 'Member of 4Ps'],
      requirements: [
        { name: 'Certificate of Grades (COG)', status: 'Verified' },
        { name: 'Certificate of Registration (COR)', status: 'Verified' },
        { name: 'Proof of Income / Certificate of Indigency', status: 'Verified' }
      ]
    },
    files: [
      { id: 'f-26', name: 'Lorenzo_Grades_COG.pdf', category: 'Certificate of Grades (COG)', type: 'application/pdf', size: '1.2 MB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-27', name: 'Lorenzo_COR.pdf', category: 'Certificate of Registration (COR)', type: 'application/pdf', size: '810 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-28', name: 'Lorenzo_4Ps_Indigency.pdf', category: 'Proof of Income / Certificate of Indigency', type: 'application/pdf', size: '750 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' }
    ]
  },
  {
    id: 'sub-seed-10',
    studentId: '2024-CAPSU-0098',
    studentName: 'William George I. Diaz',
    scholarshipType: 'Internally-Funded (Academic Full)',
    status: 'Complete',
    submittedAt: '2026-03-08T10:00:00Z',
    data: {
      studentId: '2024-CAPSU-0098',
      familyName: 'Diaz',
      firstName: 'William George',
      middleName: 'I.',
      course: 'BSFT',
      courseFull: 'Bachelor of Science in Food Technology',
      yearLevel: 'Second year',
      section: 'BSFT 2A',
      sex: 'Male',
      civilStatus: 'Single',
      scholarshipType: 'Internally-Funded (Academic Full)',
      scholarshipCategory: 'Full',
      fundingType: 'Internally-Funded',
      academicYear: 'A.Y. 2025-2026 - 2nd Semester',
      status: 'Complete',
      submittedAt: '2026-03-08T10:00:00Z',
      fatherName: 'William Diaz Sr.',
      fatherOccupation: 'Barangay Tanod',
      motherName: 'Gloria Diaz',
      motherOccupation: 'Vegetable Vendor',
      guardianOccupation: 'None',
      parentsEducationalAttainment: 'High school Graduate',
      monthlyIncome: 'below Php10,000',
      firstGenCollege: 'Yes',
      livingWith: 'Parents/Guardians',
      housingType: 'Own house',
      accessResources: ['Personal Computer/Laptop', 'Study space'],
      workingStudent: 'No',
      classifications: ['Low income family/ Economically disadvantaged student'],
      requirements: [
        { name: 'Certificate of Grades (COG)', status: 'Verified' },
        { name: 'Certificate of Registration (COR)', status: 'Verified' },
        { name: 'Proof of Income / Certificate of Indigency', status: 'Verified' }
      ]
    },
    files: [
      { id: 'f-29', name: 'Diaz_COG_Official.pdf', category: 'Certificate of Grades (COG)', type: 'application/pdf', size: '1.4 MB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-30', name: 'Diaz_COR_Semester.pdf', category: 'Certificate of Registration (COR)', type: 'application/pdf', size: '920 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-31', name: 'Diaz_Barangay_Cert.pdf', category: 'Proof of Income / Certificate of Indigency', type: 'application/pdf', size: '640 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' }
    ]
  }
];

export const defaultNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    type: 'submission',
    title: 'New Scholarship Submission Uploaded',
    description: 'Anna Marie A. Santos uploaded Certificate of Grades (COG) and Certificate of Registration (COR) for Pag-Ulikid Provincial Scholarship.',
    studentName: 'Anna Marie A. Santos',
    studentId: '2024-CAPSU-0182',
    scholarship: 'Pag-Ulikid',
    timestamp: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    read: false,
    priority: 'high',
    submissionId: 'sub-seed-1'
  },
  {
    id: 'notif-2',
    type: 'deadline',
    title: 'CHED Tulong Dunong Renewal Deadline Approaching',
    description: 'The submission window for 2nd semester renewal closes in 3 days. 18 scholars have pending document uploads.',
    scholarship: 'Tulong Dunong',
    timestamp: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    read: false,
    priority: 'high'
  },
  {
    id: 'notif-3',
    type: 'submission',
    title: 'Updated Registration Form Submitted',
    description: 'Damian James O. Emilio re-uploaded NCIP Indigenous Peoples Certificate for ANAC-IP grant validation.',
    studentName: 'Damian James O. Emilio',
    studentId: '2022-CAPSU-0041',
    scholarship: 'ANAC-IP',
    timestamp: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    read: true,
    priority: 'normal',
    submissionId: 'sub-seed-2'
  },
  {
    id: 'notif-4',
    type: 'inquiry',
    title: 'Student Inquiry on Leave of Absence (LOA)',
    description: 'Paul John N. Dela Cruz requested guidance advisory regarding LOA status for President—FLP Scholarship.',
    studentName: 'Paul John N. Dela Cruz',
    studentId: '2022-CAPSU-0089',
    scholarship: 'President—FLP',
    timestamp: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    read: true,
    priority: 'normal'
  },
  {
    id: 'notif-5',
    type: 'system',
    title: 'Masterlist Synchronized with OSAS Central',
    description: 'Academic Year 2025–2026 2nd Semester scholarship records successfully verified and backed up.',
    timestamp: new Date(Date.now() - 3 * 86400 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 3 * 86400 * 1000).toISOString(),
    read: true,
    priority: 'low'
  }
];
