import { Submission, NotificationItem } from './db';

const dummyBase64Pdf = "data:application/pdf;base64,JVBERi0xLjQKJcTl8uXrp/Og0MTGCjQgMCBvYmoKPDwgL0xlbmd0aCA1IDAgUiAvRmlsdGVyIC9GbGF0ZURlY29kZSA+PgpzdHJlYW0KeJzLSM3JyVcozy/KSVEEAELnBfUKZW5kc3RyZWFtCmVuZG9iago1IDAgb2JqCjE4CmVuZG9iagoxIDAgb2JqCjw8IC9UeXBlIC9DYXRhbG9nIC9QYWdlcyAyIDAgUiA+PgplbmRvYmoK";
const dummyBase64Image = "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='200' height='200' viewBox='0 0 200 200'><rect width='200' height='200' fill='%230f2e60'/><text x='100' y='105' fill='%23ffffff' font-family='sans-serif' font-size='14' text-anchor='middle' font-weight='bold'>2x2 Formal ID</text></svg>";

export const defaultSubmissions: Submission[] = [
  {
    id: 'sub-seed-1',
    studentId: '2024-CAPSU-0182',
    studentName: 'Anna Marie A. Santos',
    scholarshipType: 'Externally-Funded (Pag-ulikid)',
    status: 'Complete',
    submittedAt: '2026-03-11T10:00:00Z',
    data: {
      studentId: '2024-CAPSU-0182',
      familyName: 'Santos',
      firstName: 'Anna Marie',
      middleName: 'A.',
      course: 'BAEL',
      courseFull: 'Bachelor of Arts in English Language',
      yearLevel: 'Second year',
      section: 'BAEL 2A',
      sex: 'Female',
      civilStatus: 'Single',
      scholarshipType: 'Externally-Funded (Pag-ulikid)',
      scholarshipCategory: 'Pag-ulikid',
      fundingType: 'Externally-Funded',
      academicYear: 'A.Y. 2025-2026 - 2nd Semester',
      status: 'Complete',
      submittedAt: '2026-03-11T10:00:00Z',
      fatherName: 'Roberto Santos',
      fatherOccupation: 'Farmer',
      motherName: 'Elena Santos',
      motherOccupation: 'Housewife',
      guardianOccupation: 'None',
      parentsEducationalAttainment: 'High school Graduate',
      monthlyIncome: 'below Php10,000',
      firstGenCollege: 'Yes',
      livingWith: 'Parents/Guardians',
      housingType: 'Own house',
      accessResources: ['Study space', 'Textbooks and learning materials'],
      workingStudent: 'No',
      classifications: ['Low income family/ Economically disadvantaged student', 'First Generation student (Parents did not complete a college degree)'],
      requirements: [
        { name: 'Certificate of Grades (COG)', status: 'Verified' },
        { name: 'Certificate of Registration (COR)', status: 'Verified' },
        { name: 'Proof of Income / Certificate of Indigency', status: 'Verified' },
        { name: 'Certificate of Good Moral Character', status: 'Verified' },
        { name: '2x2 Recent Formal ID Photo', status: 'Verified' }
      ]
    },
    files: [
      { id: 'f-1', name: 'Santos_Certificate_of_Grades.pdf', category: 'Certificate of Grades (COG)', type: 'application/pdf', size: '1.2 MB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-2', name: 'Santos_Certificate_of_Registration.pdf', category: 'Certificate of Registration (COR)', type: 'application/pdf', size: '850 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-3', name: 'Santos_Certificate_of_Indigency.pdf', category: 'Proof of Income / Certificate of Indigency', type: 'application/pdf', size: '620 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-4', name: 'Santos_Good_Moral_Character.pdf', category: 'Certificate of Good Moral Character', type: 'application/pdf', size: '540 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-5', name: 'Santos_2x2_ID_Photo.png', category: '2x2 Recent Formal ID Photo', type: 'image/png', size: '320 KB', data: dummyBase64Image, verified: true, status: 'Verified' }
    ]
  },
  {
    id: 'sub-seed-2',
    studentId: '2024-CAPSU-0195',
    studentName: 'Patricia Jane K. Manalo',
    scholarshipType: 'Externally-Funded (CHED - Tulong Dunong)',
    status: 'Incomplete',
    submittedAt: '2026-03-11T09:30:00Z',
    data: {
      studentId: '2024-CAPSU-0195',
      familyName: 'Manalo',
      firstName: 'Patricia Jane',
      middleName: 'K.',
      course: 'BAEL',
      courseFull: 'Bachelor of Arts in English Language',
      yearLevel: 'Second year',
      section: 'BAEL 2A',
      sex: 'Female',
      civilStatus: 'Single',
      scholarshipType: 'Externally-Funded (CHED - Tulong Dunong)',
      scholarshipCategory: 'Tulong Dunong',
      fundingType: 'Externally-Funded',
      academicYear: 'A.Y. 2025-2026 - 2nd Semester',
      status: 'Incomplete',
      submittedAt: '2026-03-11T09:30:00Z',
      fatherName: 'Ricardo Manalo',
      fatherOccupation: 'Fisherman',
      motherName: 'Carmen Manalo',
      motherOccupation: 'Vendor',
      guardianOccupation: 'None',
      parentsEducationalAttainment: 'Elementary Graduate',
      monthlyIncome: 'below Php10,000',
      firstGenCollege: 'Yes',
      livingWith: 'Parents/Guardians',
      housingType: 'Own house',
      accessResources: ['Study space'],
      workingStudent: 'Yes, part-time',
      workingStudentTypeOfWork: 'Store Assistant on weekends',
      classifications: ['Low income family/ Economically disadvantaged student', 'Working Student'],
      requirements: [
        { name: 'Certificate of Grades (COG)', status: 'Verified' },
        { name: 'Certificate of Registration (COR)', status: 'Verified' },
        { name: '2x2 Recent Formal ID Photo', status: 'Verified' },
        { name: 'Proof of Income / Certificate of Indigency', status: 'Pending' }
      ]
    },
    files: [
      { id: 'f-6', name: 'Manalo_Certificate_of_Grades.pdf', category: 'Certificate of Grades (COG)', type: 'application/pdf', size: '1.1 MB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-7', name: 'Manalo_Certificate_of_Registration.pdf', category: 'Certificate of Registration (COR)', type: 'application/pdf', size: '920 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-8', name: 'Manalo_2x2_ID_Photo.png', category: '2x2 Recent Formal ID Photo', type: 'image/png', size: '310 KB', data: dummyBase64Image, verified: true, status: 'Verified' }
    ]
  },
  {
    id: 'sub-seed-3',
    studentId: '2022-CAPSU-0041',
    studentName: 'Damian James O. Emilio',
    scholarshipType: 'Externally-Funded (CHED - ANAC-IP)',
    status: 'Incomplete',
    submittedAt: '2026-03-11T08:15:00Z',
    data: {
      studentId: '2022-CAPSU-0041',
      familyName: 'Emilio',
      firstName: 'Damian James',
      middleName: 'O.',
      course: 'BSFT',
      courseFull: 'Bachelor of Science in Food Technology',
      yearLevel: 'Fourth year',
      section: 'BSFT 4A',
      sex: 'Male',
      civilStatus: 'Single',
      scholarshipType: 'Externally-Funded (CHED - ANAC-IP)',
      scholarshipCategory: 'ANAC - IP',
      fundingType: 'Externally-Funded',
      academicYear: 'A.Y. 2025-2026 - 2nd Semester',
      status: 'Incomplete',
      submittedAt: '2026-03-11T08:15:00Z',
      fatherName: 'Nestor Emilio',
      fatherOccupation: 'Indigenous Artisan / Farmer',
      motherName: 'Leonora Emilio',
      motherOccupation: 'Weaver',
      guardianOccupation: 'None',
      parentsEducationalAttainment: 'Elementary Level',
      monthlyIncome: 'below Php10,000',
      firstGenCollege: 'Yes',
      livingWith: 'Boarding house',
      housingType: 'Boarding house',
      accessResources: ['Study space'],
      workingStudent: 'No',
      classifications: ['Indigenous Peoples (IPs)', 'From geographically isolated & disadvantaged area (GIDA)'],
      requirements: [
        { name: 'Certificate of Grades (COG)', status: 'Verified' },
        { name: 'Certificate of Registration (COR)', status: 'Verified' },
        { name: 'Proof of Income / Certificate of Indigency', status: 'Pending' }
      ]
    },
    files: [
      { id: 'f-9', name: 'Emilio_COG_Semester.pdf', category: 'Certificate of Grades (COG)', type: 'application/pdf', size: '1.4 MB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-10', name: 'Emilio_COR_Assessment.pdf', category: 'Certificate of Registration (COR)', type: 'application/pdf', size: '780 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-11', name: 'Emilio_NCIP_Certificate.pdf', category: 'Proof of Income / Certificate of Indigency', type: 'application/pdf', size: '1.8 MB', data: dummyBase64Pdf, verified: false, status: 'Pending', remarks: 'NCIP seal validation in progress' }
    ]
  },
  {
    id: 'sub-seed-4',
    studentId: '2022-CAPSU-0089',
    studentName: 'Paul John N. Dela Cruz',
    scholarshipType: 'Internally-Funded (President - FLP)',
    status: 'Incomplete',
    submittedAt: '2026-03-11T07:45:00Z',
    data: {
      studentId: '2022-CAPSU-0089',
      familyName: 'Dela Cruz',
      firstName: 'Paul John',
      middleName: 'N.',
      course: 'BSOA',
      courseFull: 'Bachelor of Science in Office Administration',
      yearLevel: 'Fourth year',
      section: 'BSOA 4A',
      sex: 'Male',
      civilStatus: 'Single',
      scholarshipType: 'Internally-Funded (President - FLP)',
      scholarshipCategory: 'President - FLP',
      fundingType: 'Internally-Funded',
      academicYear: 'A.Y. 2025-2026 - 2nd Semester',
      status: 'Incomplete',
      submittedAt: '2026-03-11T07:45:00Z',
      fatherName: 'Federico Dela Cruz',
      fatherOccupation: 'Tricycle Driver',
      motherName: 'Maria Dela Cruz',
      motherOccupation: 'Sari-sari Store Owner',
      guardianOccupation: 'None',
      parentsEducationalAttainment: 'High School Level',
      monthlyIncome: 'Php10,001 - 20,000',
      firstGenCollege: 'Yes',
      livingWith: 'Parents/Guardians',
      housingType: 'Own house',
      accessResources: ['Personal Computer/Laptop', 'Internet Connection', 'Study space'],
      workingStudent: 'No',
      classifications: ['Regular student (I do not belong to any of this group classification)'],
      requirements: [
        { name: 'Certificate of Grades (COG)', status: 'Verified' },
        { name: 'Certificate of Registration (COR)', status: 'Verified' }
      ]
    },
    files: [
      { id: 'f-12', name: 'DelaCruz_Transcript.pdf', category: 'Certificate of Grades (COG)', type: 'application/pdf', size: '1.5 MB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-13', name: 'DelaCruz_COR.pdf', category: 'Certificate of Registration (COR)', type: 'application/pdf', size: '890 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' }
    ]
  },
  {
    id: 'sub-seed-5',
    studentId: '2023-CAPSU-0312',
    studentName: 'Charlotte Alexis N. Tuvera',
    scholarshipType: 'Internally-Funded (Valedictorian)',
    status: 'Incomplete',
    submittedAt: '2026-03-10T14:20:00Z',
    data: {
      studentId: '2023-CAPSU-0312',
      familyName: 'Tuvera',
      firstName: 'Charlotte Alexis',
      middleName: 'N.',
      course: 'BSCS',
      courseFull: 'Bachelor of Science in Computer Science',
      yearLevel: 'Third year',
      section: 'BSCS 3A',
      sex: 'Female',
      civilStatus: 'Single',
      scholarshipType: 'Internally-Funded (Valedictorian)',
      scholarshipCategory: 'Valedictorian',
      fundingType: 'Internally-Funded',
      academicYear: 'A.Y. 2025-2026 - 2nd Semester',
      status: 'Incomplete',
      submittedAt: '2026-03-10T14:20:00Z',
      fatherName: 'Alexander Tuvera',
      fatherOccupation: 'Mechanic',
      motherName: 'Corazon Tuvera',
      motherOccupation: 'Seamstress',
      guardianOccupation: 'None',
      parentsEducationalAttainment: 'High school Graduate',
      monthlyIncome: 'Php10,001 - 20,000',
      firstGenCollege: 'No',
      livingWith: 'Parents/Guardians',
      housingType: 'Own house',
      accessResources: ['Personal Computer/Laptop', 'Internet Connection', 'Study space', 'Textbooks and learning materials'],
      workingStudent: 'No',
      classifications: ['Regular student (I do not belong to any of this group classification)'],
      requirements: [
        { name: 'Certificate of Grades (COG)', status: 'Verified' },
        { name: 'Certificate of Registration (COR)', status: 'Verified' }
      ]
    },
    files: [
      { id: 'f-14', name: 'Tuvera_Academic_COG.pdf', category: 'Certificate of Grades (COG)', type: 'application/pdf', size: '1.3 MB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-15', name: 'Tuvera_COR_Current.pdf', category: 'Certificate of Registration (COR)', type: 'application/pdf', size: '910 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' }
    ]
  },
  {
    id: 'sub-seed-6',
    studentId: '2023-CAPSU-0205',
    studentName: 'Michael G. Burata',
    scholarshipType: 'Internally-Funded (Academic Full)',
    status: 'Complete',
    submittedAt: '2026-03-10T11:00:00Z',
    data: {
      studentId: '2023-CAPSU-0205',
      familyName: 'Burata',
      firstName: 'Michael',
      middleName: 'G.',
      course: 'BSCS',
      courseFull: 'Bachelor of Science in Computer Science',
      yearLevel: 'Third year',
      section: 'BSCS 3A',
      sex: 'Male',
      civilStatus: 'Single',
      scholarshipType: 'Internally-Funded (Academic Full)',
      scholarshipCategory: 'Full',
      fundingType: 'Internally-Funded',
      academicYear: 'A.Y. 2025-2026 - 2nd Semester',
      status: 'Complete',
      submittedAt: '2026-03-10T11:00:00Z',
      fatherName: 'Gregorio Burata',
      fatherOccupation: 'Carpenter',
      motherName: 'Teresa Burata',
      motherOccupation: 'Barangay Health Worker',
      guardianOccupation: 'None',
      parentsEducationalAttainment: 'High school Graduate',
      monthlyIncome: 'below Php10,000',
      firstGenCollege: 'Yes',
      livingWith: 'Parents/Guardians',
      housingType: 'Own house',
      accessResources: ['Personal Computer/Laptop', 'Internet Connection', 'Study space'],
      workingStudent: 'No',
      classifications: ['Low income family/ Economically disadvantaged student'],
      requirements: [
        { name: 'Certificate of Grades (COG)', status: 'Verified' },
        { name: 'Certificate of Registration (COR)', status: 'Verified' },
        { name: 'Proof of Income / Certificate of Indigency', status: 'Verified' },
        { name: 'Certificate of Good Moral Character', status: 'Verified' }
      ]
    },
    files: [
      { id: 'f-16', name: 'Burata_COG_GWA125.pdf', category: 'Certificate of Grades (COG)', type: 'application/pdf', size: '1.6 MB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-17', name: 'Burata_COR_Official.pdf', category: 'Certificate of Registration (COR)', type: 'application/pdf', size: '840 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-18', name: 'Burata_Indigency.pdf', category: 'Proof of Income / Certificate of Indigency', type: 'application/pdf', size: '590 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-19', name: 'Burata_GoodMoral.pdf', category: 'Certificate of Good Moral Character', type: 'application/pdf', size: '510 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' }
    ]
  },
  {
    id: 'sub-seed-7',
    studentId: '2023-CAPSU-0118',
    studentName: 'Chery Joy M. Marcelino',
    scholarshipType: 'Externally-Funded (CHED - Tulong Dunong)',
    status: 'Complete',
    submittedAt: '2026-03-10T09:10:00Z',
    data: {
      studentId: '2023-CAPSU-0118',
      familyName: 'Marcelino',
      firstName: 'Chery Joy',
      middleName: 'M.',
      course: 'BSCS',
      courseFull: 'Bachelor of Science in Computer Science',
      yearLevel: 'Third year',
      section: 'BSCS 3A',
      sex: 'Female',
      civilStatus: 'Single',
      scholarshipType: 'Externally-Funded (CHED - Tulong Dunong)',
      scholarshipCategory: 'Tulong Dunong',
      fundingType: 'Externally-Funded',
      academicYear: 'A.Y. 2025-2026 - 2nd Semester',
      status: 'Complete',
      submittedAt: '2026-03-10T09:10:00Z',
      fatherName: 'Manuel Marcelino',
      fatherOccupation: 'Security Guard',
      motherName: 'Joy Marcelino',
      motherOccupation: 'Housewife',
      guardianOccupation: 'None',
      parentsEducationalAttainment: 'High school Graduate',
      monthlyIncome: 'below Php10,000',
      firstGenCollege: 'Yes',
      livingWith: 'Parents/Guardians',
      housingType: 'Own house',
      accessResources: ['Personal Computer/Laptop', 'Study space'],
      workingStudent: 'No',
      classifications: ['Low income family/ Economically disadvantaged student', 'First Generation student (Parents did not complete a college degree)'],
      requirements: [
        { name: 'Certificate of Grades (COG)', status: 'Verified' },
        { name: 'Certificate of Registration (COR)', status: 'Verified' },
        { name: 'Proof of Income / Certificate of Indigency', status: 'Verified' }
      ]
    },
    files: [
      { id: 'f-20', name: 'Marcelino_COG.pdf', category: 'Certificate of Grades (COG)', type: 'application/pdf', size: '1.2 MB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-21', name: 'Marcelino_COR.pdf', category: 'Certificate of Registration (COR)', type: 'application/pdf', size: '820 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-22', name: 'Marcelino_Indigency.pdf', category: 'Proof of Income / Certificate of Indigency', type: 'application/pdf', size: '610 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' }
    ]
  },
  {
    id: 'sub-seed-8',
    studentId: '2024-CAPSU-0044',
    studentName: 'Jessica Mae E. Dela Cruz',
    scholarshipType: 'Internally-Funded (Academic Partial)',
    status: 'Complete',
    submittedAt: '2026-03-09T16:00:00Z',
    data: {
      studentId: '2024-CAPSU-0044',
      familyName: 'Dela Cruz',
      firstName: 'Jessica Mae',
      middleName: 'E.',
      course: 'BSCS',
      courseFull: 'Bachelor of Science in Computer Science',
      yearLevel: 'Second year',
      section: 'BSCS 2A',
      sex: 'Female',
      civilStatus: 'Single',
      scholarshipType: 'Internally-Funded (Academic Partial)',
      scholarshipCategory: 'Partial',
      fundingType: 'Internally-Funded',
      academicYear: 'A.Y. 2025-2026 - 2nd Semester',
      status: 'Complete',
      submittedAt: '2026-03-09T16:00:00Z',
      fatherName: 'Eduardo Dela Cruz',
      fatherOccupation: 'Electrician',
      motherName: 'Milagros Dela Cruz',
      motherOccupation: 'Dressmaker',
      guardianOccupation: 'None',
      parentsEducationalAttainment: 'College Level',
      monthlyIncome: 'Php10,001 - 20,000',
      firstGenCollege: 'No',
      livingWith: 'Parents/Guardians',
      housingType: 'Own house',
      accessResources: ['Personal Computer/Laptop', 'Internet Connection', 'Study space'],
      workingStudent: 'No',
      classifications: ['Regular student (I do not belong to any of this group classification)'],
      requirements: [
        { name: 'Certificate of Grades (COG)', status: 'Verified' },
        { name: 'Certificate of Registration (COR)', status: 'Verified' },
        { name: 'Certificate of Good Moral Character', status: 'Verified' }
      ]
    },
    files: [
      { id: 'f-23', name: 'Jessica_COG_Official.pdf', category: 'Certificate of Grades (COG)', type: 'application/pdf', size: '1.3 MB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-24', name: 'Jessica_COR_Form.pdf', category: 'Certificate of Registration (COR)', type: 'application/pdf', size: '890 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-25', name: 'Jessica_Moral.pdf', category: 'Certificate of Good Moral Character', type: 'application/pdf', size: '540 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' }
    ]
  },
  {
    id: 'sub-seed-9',
    studentId: '2025-CAPSU-0112',
    studentName: 'Mark Josh P. Lorenzo',
    scholarshipType: 'Externally-Funded (Tertiary Education Subsidy - TES)',
    status: 'Complete',
    submittedAt: '2026-03-09T14:30:00Z',
    data: {
      studentId: '2025-CAPSU-0112',
      familyName: 'Lorenzo',
      firstName: 'Mark Josh',
      middleName: 'P.',
      course: 'BSOA',
      courseFull: 'Bachelor of Science in Office Administration',
      yearLevel: 'First year',
      section: 'BSOA 1A',
      sex: 'Male',
      civilStatus: 'Single',
      scholarshipType: 'Externally-Funded (Tertiary Education Subsidy - TES)',
      scholarshipCategory: 'TES',
      fundingType: 'Externally-Funded',
      academicYear: 'A.Y. 2025-2026 - 2nd Semester',
      status: 'Complete',
      submittedAt: '2026-03-09T14:30:00Z',
      fatherName: 'Jose Lorenzo',
      fatherOccupation: 'Farmer',
      motherName: 'Lina Lorenzo',
      motherOccupation: 'Housewife',
      guardianOccupation: 'None',
      parentsEducationalAttainment: 'High School Level',
      monthlyIncome: 'below Php10,000',
      firstGenCollege: 'Yes',
      livingWith: 'Parents/Guardians',
      housingType: 'Own house',
      accessResources: ['Study space'],
      workingStudent: 'No',
      classifications: ['Low income family/ Economically disadvantaged student', 'Member of 4Ps'],
      requirements: [
        { name: 'Certificate of Grades (COG)', status: 'Verified' },
        { name: 'Certificate of Registration (COR)', status: 'Verified' },
        { name: 'Proof of Income / Certificate of Indigency', status: 'Verified' }
      ]
    },
    files: [
      { id: 'f-26', name: 'Lorenzo_Grades_COG.pdf', category: 'Certificate of Grades (COG)', type: 'application/pdf', size: '1.2 MB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-27', name: 'Lorenzo_COR.pdf', category: 'Certificate of Registration (COR)', type: 'application/pdf', size: '810 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-28', name: 'Lorenzo_4Ps_Indigency.pdf', category: 'Proof of Income / Certificate of Indigency', type: 'application/pdf', size: '750 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' }
    ]
  },
  {
    id: 'sub-seed-10',
    studentId: '2024-CAPSU-0098',
    studentName: 'William George I. Diaz',
    scholarshipType: 'Internally-Funded (Academic Full)',
    status: 'Complete',
    submittedAt: '2026-03-08T10:00:00Z',
    data: {
      studentId: '2024-CAPSU-0098',
      familyName: 'Diaz',
      firstName: 'William George',
      middleName: 'I.',
      course: 'BSFT',
      courseFull: 'Bachelor of Science in Food Technology',
      yearLevel: 'Second year',
      section: 'BSFT 2A',
      sex: 'Male',
      civilStatus: 'Single',
      scholarshipType: 'Internally-Funded (Academic Full)',
      scholarshipCategory: 'Full',
      fundingType: 'Internally-Funded',
      academicYear: 'A.Y. 2025-2026 - 2nd Semester',
      status: 'Complete',
      submittedAt: '2026-03-08T10:00:00Z',
      fatherName: 'William Diaz Sr.',
      fatherOccupation: 'Barangay Tanod',
      motherName: 'Gloria Diaz',
      motherOccupation: 'Vegetable Vendor',
      guardianOccupation: 'None',
      parentsEducationalAttainment: 'High school Graduate',
      monthlyIncome: 'below Php10,000',
      firstGenCollege: 'Yes',
      livingWith: 'Parents/Guardians',
      housingType: 'Own house',
      accessResources: ['Personal Computer/Laptop', 'Study space'],
      workingStudent: 'No',
      classifications: ['Low income family/ Economically disadvantaged student'],
      requirements: [
        { name: 'Certificate of Grades (COG)', status: 'Verified' },
        { name: 'Certificate of Registration (COR)', status: 'Verified' },
        { name: 'Proof of Income / Certificate of Indigency', status: 'Verified' }
      ]
    },
    files: [
      { id: 'f-29', name: 'Diaz_COG_Official.pdf', category: 'Certificate of Grades (COG)', type: 'application/pdf', size: '1.4 MB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-30', name: 'Diaz_COR_Semester.pdf', category: 'Certificate of Registration (COR)', type: 'application/pdf', size: '920 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' },
      { id: 'f-31', name: 'Diaz_Barangay_Cert.pdf', category: 'Proof of Income / Certificate of Indigency', type: 'application/pdf', size: '640 KB', data: dummyBase64Pdf, verified: true, status: 'Verified' }
    ]
  }
];

export const defaultNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    type: 'submission',
    title: 'New Scholarship Submission Uploaded',
    description: 'Anna Marie A. Santos uploaded Certificate of Grades (COG) and Certificate of Registration (COR) for Pag-Ulikid Provincial Scholarship.',
    studentName: 'Anna Marie A. Santos',
    studentId: '2024-CAPSU-0182',
    scholarship: 'Pag-Ulikid',
    timestamp: '10 minutes ago',
    read: false,
    priority: 'high'
  },
  {
    id: 'notif-2',
    type: 'deadline',
    title: 'CHED Tulong Dunong Renewal Deadline Approaching',
    description: 'The submission window for 2nd semester renewal closes in 3 days. 18 scholars have pending document uploads.',
    scholarship: 'Tulong Dunong',
    timestamp: '2 hours ago',
    read: false,
    priority: 'high'
  },
  {
    id: 'notif-3',
    type: 'submission',
    title: 'Updated Registration Form Submitted',
    description: 'Damian James O. Emilio re-uploaded NCIP Indigenous Peoples Certificate for ANAC-IP grant validation.',
    studentName: 'Damian James O. Emilio',
    studentId: '2022-CAPSU-0041',
    scholarship: 'ANAC-IP',
    timestamp: '5 hours ago',
    read: true,
    priority: 'normal'
  },
  {
    id: 'notif-4',
    type: 'inquiry',
    title: 'Student Inquiry on Leave of Absence (LOA)',
    description: 'Paul John N. Dela Cruz requested guidance advisory regarding LOA status for President—FLP Scholarship.',
    studentName: 'Paul John N. Dela Cruz',
    studentId: '2022-CAPSU-0089',
    scholarship: 'President—FLP',
    timestamp: 'Yesterday at 3:45 PM',
    read: true,
    priority: 'normal'
  },
  {
    id: 'notif-5',
    type: 'system',
    title: 'Masterlist Synchronized with OSAS Central',
    description: 'Academic Year 2025–2026 2nd Semester scholarship records successfully verified and backed up.',
    timestamp: 'Aug 17, 2026',
    read: true,
    priority: 'low'
  }
];
