const fs = require('fs');

let content = fs.readFileSync('src/pages/guidance/index.tsx', 'utf-8');

// 1. Ensure Printer is imported
if (!content.includes('Printer,')) {
  content = content.replace("import { Upload", "import { Printer, Upload");
}

// 2. Replace the modal entirely
const modalStart = content.indexOf('{selectedSubmission && (');
// Find the closing of selectedSubmission modal. It's followed by `</main>` or similar.
const modalEnd = content.indexOf('</main>', modalStart);

const newModal = `
      {selectedSubmission && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center p-4 z-50 print:p-0 print:bg-white print:block print:relative print:z-0">
          <div className="bg-white rounded-2xl w-full max-w-4xl max-h-[90vh] overflow-hidden flex flex-col shadow-2xl print:max-h-none print:shadow-none print:rounded-none">
            
            {/* Header */}
            <div className="p-6 border-b border-gray-100 flex justify-between items-center bg-gray-50/50 print:hidden">
              <div>
                <h3 className="text-xl font-bold text-gray-900">{selectedSubmission.data?.firstName} {selectedSubmission.data?.familyName}</h3>
                <p className="text-sm text-gray-500 mt-1">{selectedSubmission.data?.scholarshipCategory || 'Scholarship Application'} &bull; {new Date(selectedSubmission.submittedAt).toLocaleDateString()}</p>
              </div>
              <div className="flex gap-2">
                <button onClick={() => window.print()} className="p-2 text-gray-600 hover:bg-gray-200 rounded-full transition-colors" title="Print Application">
                  <Printer className="w-5 h-5" />
                </button>
                <button onClick={() => setSelectedSubmission(null)} className="p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-600 rounded-full transition-colors">
                  <X className="w-5 h-5" />
                </button>
              </div>
            </div>
            
            {/* Print Header (Only visible when printing) */}
            <div className="hidden print:block mb-8 text-center border-b pb-4">
              <h1 className="text-2xl font-bold">OFFICIAL SCHOLARSHIP APPLICATION</h1>
              <p className="text-sm mt-1 text-gray-600">Generated by Web-Based Scholars System</p>
              <div className="mt-4 flex justify-between text-sm text-left">
                <p><strong>Applicant:</strong> {selectedSubmission.data?.familyName}, {selectedSubmission.data?.firstName} {selectedSubmission.data?.middleName}</p>
                <p><strong>Date Submitted:</strong> {new Date(selectedSubmission.submittedAt).toLocaleDateString()}</p>
              </div>
              <div className="flex justify-between text-sm text-left">
                <p><strong>Scholarship Type:</strong> {selectedSubmission.data?.fundingType} ({selectedSubmission.data?.scholarshipCategory})</p>
                <p><strong>Status:</strong> {selectedSubmission.status}</p>
              </div>
            </div>

            <div className="p-6 flex-1 overflow-y-auto bg-gray-50 print:bg-white print:overflow-visible">
              
              {/* Form Data Rendering */}
              {selectedSubmission.data && (
                <div className="space-y-6 mb-8 print:space-y-4">
                  
                  {/* Demographics */}
                  <div className="bg-white p-5 rounded-xl border border-gray-200 print:border-none print:p-0 print:border-b print:rounded-none">
                    <h4 className="text-sm font-bold text-[#0f2e60] uppercase tracking-wider mb-4 print:text-black">A. Personal Demographics</h4>
                    <div className="grid grid-cols-2 gap-y-4 gap-x-8 text-sm">
                      <div><span className="text-gray-500 print:text-gray-700">Course:</span> <strong className="block">{selectedSubmission.data.course}</strong></div>
                      <div><span className="text-gray-500 print:text-gray-700">Year & Section:</span> <strong className="block">{selectedSubmission.data.yearLevel} - {selectedSubmission.data.section}</strong></div>
                      <div><span className="text-gray-500 print:text-gray-700">Sex:</span> <strong className="block">{selectedSubmission.data.sex}</strong></div>
                      <div><span className="text-gray-500 print:text-gray-700">Civil Status:</span> <strong className="block">{selectedSubmission.data.civilStatus}</strong></div>
                    </div>
                  </div>

                  {/* Family Background */}
                  <div className="bg-white p-5 rounded-xl border border-gray-200 print:border-none print:p-0 print:border-b print:rounded-none">
                    <h4 className="text-sm font-bold text-[#0f2e60] uppercase tracking-wider mb-4 print:text-black">B. Family Background</h4>
                    <div className="grid grid-cols-2 gap-y-4 gap-x-8 text-sm">
                      <div><span className="text-gray-500 print:text-gray-700">Father's Occupation:</span> <strong className="block">{selectedSubmission.data.fatherOccupation || 'N/A'}</strong></div>
                      <div><span className="text-gray-500 print:text-gray-700">Mother's Occupation:</span> <strong className="block">{selectedSubmission.data.motherOccupation || 'N/A'}</strong></div>
                      <div><span className="text-gray-500 print:text-gray-700">Highest Educ. Attainment:</span> <strong className="block">{selectedSubmission.data.parentsEducationalAttainment || 'N/A'}</strong></div>
                      <div><span className="text-gray-500 print:text-gray-700">Monthly Income:</span> <strong className="block">{selectedSubmission.data.monthlyIncome || 'N/A'}</strong></div>
                      <div><span className="text-gray-500 print:text-gray-700">First Generation College:</span> <strong className="block">{selectedSubmission.data.firstGenCollege || 'N/A'}</strong></div>
                    </div>
                  </div>

                  {/* Living Condition */}
                  <div className="bg-white p-5 rounded-xl border border-gray-200 print:border-none print:p-0 print:border-b print:rounded-none">
                    <h4 className="text-sm font-bold text-[#0f2e60] uppercase tracking-wider mb-4 print:text-black">C. Living Condition & Classification</h4>
                    <div className="grid grid-cols-2 gap-y-4 gap-x-8 text-sm">
                      <div><span className="text-gray-500 print:text-gray-700">Living With:</span> <strong className="block">{selectedSubmission.data.livingWith || 'N/A'}</strong></div>
                      <div><span className="text-gray-500 print:text-gray-700">Housing Type:</span> <strong className="block">{selectedSubmission.data.housingType || 'N/A'}</strong></div>
                      <div><span className="text-gray-500 print:text-gray-700">Student Classification:</span> <strong className="block">{selectedSubmission.data.classification || 'N/A'}</strong></div>
                    </div>
                  </div>

                </div>
              )}

              {/* Attachments Section */}
              <h4 className="text-sm font-bold text-[#0f2e60] uppercase tracking-wider mb-4 print:hidden">Submitted Documents</h4>
              
              {(!selectedSubmission.files || Object.keys(selectedSubmission.files).length === 0) ? (
                <div className="text-center p-8 text-gray-500 bg-white rounded-xl border border-gray-200 border-dashed print:hidden">
                  No documents found for this submission.
                </div>
              ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 print:hidden">
                  {Object.entries(selectedSubmission.files).map(([key, file]: [string, any]) => (
                    <div key={key} className="bg-white border border-gray-200 rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-shadow">
                      <div className="p-3 border-b border-gray-100 bg-gray-50/50 flex items-center justify-between">
                        <span className="font-medium text-sm text-gray-700 truncate">{file.name}</span>
                        <span className="text-xs bg-gray-200 text-gray-600 px-2 py-0.5 rounded-md font-medium uppercase">{key}</span>
                      </div>
                      <div className="aspect-video bg-gray-100 relative group overflow-hidden">
                        {file.data.startsWith('data:image/') ? (
                          <img src={file.data} alt={file.name} className="w-full h-full object-cover" />
                        ) : (
                          <div className="absolute inset-0 flex flex-col items-center justify-center text-gray-400">
                            <FileText className="w-12 h-12 mb-2 opacity-50" />
                            <span className="text-sm font-medium">PDF Document</span>
                          </div>
                        )}
                        <div className="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                          <a href={file.data} download={file.name} className="bg-white text-gray-900 px-4 py-2 rounded-lg text-sm font-medium hover:bg-blue-50 transition-colors shadow-lg">Download</a>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}
              
              {/* Signature area for print only */}
              <div className="hidden print:flex justify-between mt-20 pt-8 border-t border-gray-300">
                <div className="text-center">
                  <div className="w-48 border-b border-black mb-1"></div>
                  <span className="text-sm uppercase font-bold">{selectedSubmission.data?.firstName} {selectedSubmission.data?.familyName}</span>
                  <div className="text-xs text-gray-600">Applicant Signature</div>
                </div>
                <div className="text-center">
                  <div className="w-48 border-b border-black mb-1"></div>
                  <span className="text-sm uppercase font-bold">Guidance Director</span>
                  <div className="text-xs text-gray-600">Approved By</div>
                </div>
              </div>

            </div>
            
            <div className="p-6 border-t border-gray-100 bg-white flex justify-between items-center gap-4 print:hidden">
              <div className="flex items-center gap-3">
                <span className="text-sm font-medium text-gray-600">Current Status:</span>
                <span className={cn(
                  "px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider",
                  selectedSubmission.status === 'Approved' ? "bg-green-100 text-green-700" :
                  selectedSubmission.status === 'Rejected' ? "bg-red-100 text-red-700" :
                  "bg-amber-100 text-amber-700"
                )}>
                  {selectedSubmission.status}
                </span>
              </div>
              <div className="flex gap-2">
                <button onClick={() => updateStatus(selectedSubmission.id, 'Rejected')} className="px-4 py-2 text-red-600 hover:bg-red-50 rounded-lg text-sm font-medium transition-colors">Reject</button>
                <button onClick={() => updateStatus(selectedSubmission.id, 'Approved')} className="px-6 py-2 bg-green-600 text-white hover:bg-green-700 rounded-lg text-sm font-medium transition-colors shadow-sm">Approve</button>
              </div>
            </div>
          </div>
        </div>
      )}
      `;

content = content.slice(0, modalStart) + newModal + content.slice(modalEnd);
fs.writeFileSync('src/pages/guidance/index.tsx', content);
