export interface StudentBreakdownItem {
  id: string;
  studentId: string;
  student: string;
  yearLevel: string;
  course: string;
  courseFull: string;
  category: 'Internally-Funded' | 'Externally-Funded';
  subType: string;
  allocation: string;
  gender: 'Male' | 'Female';
  email: string;
  phone: string;
  address: string;
  gwa: string;
  units: number;
  status: 'Complete' | 'Incomplete';
  dateSubmitted: string;
  requirements: { name: string; status: 'Verified' | 'Pending' | 'Missing' }[];
  remarks: string;
  files?: any[];
  data?: any;
}

export const scholarshipDataMapping: Record<string, Record<string, string[]>> = {
  'Internally-Funded': {
    'Entrance': ['Valedictorian', 'Salutatorian'],
    'Academic': ['Full', 'Partial', 'Regional', 'National'],
    'Socio-cultural': ['Regional', 'National'],
    'Institutional': [
      'Dependent of Faculty or Staff',
      'President - SSC',
      'President - FLP',
      'Editor-in-Chief (Campus Publication)',
      'CAPSU Band / Chorale'
    ]
  },
  'Externally-Funded': {
    'CHED': [
      'Congressional District',
      'One Town One Scholar',
      'Tulong Dunong',
      'ANAC - IP',
      'Pag - ulikid',
      'Barangay (Legal dependents of Brgy. Officials)',
      'ESGP - PA',
      'UniFast',
      'Tertiary Education Subsidy (TES)'
    ],
    'Merit': ['VIC', 'Capizeño Circle', 'DOST', 'GRF', 'LGU: Barangay'],
    'DSWD': []
  }
};

export const initialBreakdownData: StudentBreakdownItem[] = [
  { 
    id: '1', 
    studentId: '2024-CAPSU-0182',
    student: 'Anna Marie A. Santos', 
    yearLevel: '2nd year', 
    course: 'BAEL', 
    courseFull: 'Bachelor of Arts in English Language',
    category: 'Externally-Funded', 
    subType: 'CHED', 
    allocation: 'Pag-Ulikid',
    gender: 'Female',
    email: 'anna.santos@capsu.edu.ph',
    phone: '+63 917 842 1930',
    address: 'Brgy. Poblacion, Tapaz, Capiz',
    gwa: '1.42',
    units: 21,
    status: 'Complete',
    dateSubmitted: 'Aug 12, 2026',
    requirements: [
      { name: 'Certificate of Grades (COG)', status: 'Verified' },
      { name: 'Certificate of Registration (COR)', status: 'Verified' },
      { name: 'Certificate of Indigency', status: 'Verified' },
      { name: 'Good Moral Character', status: 'Verified' },
      { name: '2x2 ID Photo', status: 'Verified' },
    ],
    remarks: 'Application verified. Meets all academic and financial requirements for Pag-Ulikid Provincial Scholarship.'
  },
  { 
    id: '2', 
    studentId: '2024-CAPSU-0195',
    student: 'Patricia Jane K. Manalo', 
    yearLevel: '2nd year', 
    course: 'BAEL', 
    courseFull: 'Bachelor of Arts in English Language',
    category: 'Externally-Funded', 
    subType: 'CHED', 
    allocation: 'Tulong Dunong',
    gender: 'Female',
    email: 'patricia.manalo@capsu.edu.ph',
    phone: '+63 928 411 9021',
    address: 'Brgy. San Nicolas, Tapaz, Capiz',
    gwa: '1.68',
    units: 21,
    status: 'Complete',
    dateSubmitted: 'Aug 11, 2026',
    requirements: [
      { name: 'Certificate of Grades (COG)', status: 'Verified' },
      { name: 'Certificate of Registration (COR)', status: 'Verified' },
      { name: 'ITR / Proof of Income', status: 'Verified' },
      { name: 'Good Moral Character', status: 'Verified' },
      { name: '2x2 ID Photo', status: 'Verified' },
    ],
    remarks: 'CHED Tulong Dunong grantee. All documents validated.'
  },
  { 
    id: '3', 
    studentId: '2022-CAPSU-0041',
    student: 'Damian James O. Emilio', 
    yearLevel: '4th year', 
    course: 'BSFT', 
    courseFull: 'Bachelor of Science in Food Technology',
    category: 'Externally-Funded', 
    subType: 'CHED', 
    allocation: 'ANAC-IP',
    gender: 'Male',
    email: 'damian.emilio@capsu.edu.ph',
    phone: '+63 905 678 1234',
    address: 'Brgy. San Jose, Tapaz, Capiz',
    gwa: '1.75',
    units: 24,
    status: 'Complete',
    dateSubmitted: 'Aug 09, 2026',
    requirements: [
      { name: 'Certificate of Grades (COG)', status: 'Verified' },
      { name: 'Certificate of Registration (COR)', status: 'Verified' },
      { name: 'NCIP Indigenous Peoples Certificate', status: 'Verified' },
      { name: 'Good Moral Character', status: 'Verified' },
      { name: '2x2 ID Photo', status: 'Verified' },
    ],
    remarks: 'Indigenous Peoples (ANAC-IP) beneficiary. Endorsed by NCIP.'
  },
  { 
    id: '4', 
    studentId: '2022-CAPSU-0089',
    student: 'Paul John N. Dela Cruz', 
    yearLevel: '4th year', 
    course: 'BSOA', 
    courseFull: 'Bachelor of Science in Office Administration',
    category: 'Internally-Funded', 
    subType: 'Institutional', 
    allocation: 'President—FLP',
    gender: 'Male',
    email: 'pauljohn.delacruz@capsu.edu.ph',
    phone: '+63 919 555 4321',
    address: 'Brgy. Camburanan, Tapaz, Capiz',
    gwa: '1.30',
    units: 21,
    status: 'Complete',
    dateSubmitted: 'Aug 14, 2026',
    requirements: [
      { name: 'Certificate of Grades (COG)', status: 'Verified' },
      { name: 'Certificate of Registration (COR)', status: 'Verified' },
      { name: 'Student Leadership Certificate', status: 'Verified' },
      { name: 'Good Moral Character', status: 'Verified' },
      { name: '2x2 ID Photo', status: 'Verified' },
    ],
    remarks: 'President’s Future Leaders Program scholar. Outstanding extracurricular and academic record.'
  },
  { 
    id: '5', 
    studentId: '2023-CAPSU-0112',
    student: 'Charlotte Alexis N. Tuvera', 
    yearLevel: '3rd year', 
    course: 'BSCS', 
    courseFull: 'Bachelor of Science in Computer Science',
    category: 'Internally-Funded', 
    subType: 'Institutional', 
    allocation: 'Dependent of Faculty or Staff',
    gender: 'Female',
    email: 'charlotte.tuvera@capsu.edu.ph',
    phone: '+63 945 123 8899',
    address: 'CAPSU Staff Housing, Tapaz Campus',
    gwa: '1.55',
    units: 23,
    status: 'Complete',
    dateSubmitted: 'Aug 10, 2026',
    requirements: [
      { name: 'Certificate of Grades (COG)', status: 'Verified' },
      { name: 'Certificate of Registration (COR)', status: 'Verified' },
      { name: 'HR Faculty Dependent Certification', status: 'Verified' },
      { name: 'Good Moral Character', status: 'Verified' },
      { name: '2x2 ID Photo', status: 'Verified' },
    ],
    remarks: 'Verified dependent of full-time CAPSU faculty.'
  },
  { 
    id: '6', 
    studentId: '2023-CAPSU-0144',
    student: 'Michael O. Burata', 
    yearLevel: '3rd year', 
    course: 'BSCS', 
    courseFull: 'Bachelor of Science in Computer Science',
    category: 'Internally-Funded', 
    subType: 'Socio-cultural', 
    allocation: 'Regional',
    gender: 'Male',
    email: 'michael.burata@capsu.edu.ph',
    phone: '+63 939 778 0012',
    address: 'Brgy. Roosevelt, Tapaz, Capiz',
    gwa: '1.80',
    units: 23,
    status: 'Complete',
    dateSubmitted: 'Aug 08, 2026',
    requirements: [
      { name: 'Certificate of Grades (COG)', status: 'Verified' },
      { name: 'Certificate of Registration (COR)', status: 'Verified' },
      { name: 'Regional Cultural Artist Certification', status: 'Verified' },
      { name: 'Good Moral Character', status: 'Verified' },
      { name: '2x2 ID Photo', status: 'Verified' },
    ],
    remarks: 'Socio-Cultural Ensemble regional participant.'
  },
  { 
    id: '7', 
    studentId: '2023-CAPSU-0201',
    student: 'Chery Joy M. Marcelino', 
    yearLevel: '3rd year', 
    course: 'BSCS', 
    courseFull: 'Bachelor of Science in Computer Science',
    category: 'Internally-Funded', 
    subType: 'Academic', 
    allocation: 'Partial',
    gender: 'Female',
    email: 'cheryjoy.marcelino@capsu.edu.ph',
    phone: '+63 916 333 7788',
    address: 'Brgy. Agpalali, Tapaz, Capiz',
    gwa: '1.65',
    units: 23,
    status: 'Complete',
    dateSubmitted: 'Aug 13, 2026',
    requirements: [
      { name: 'Certificate of Grades (COG)', status: 'Verified' },
      { name: 'Certificate of Registration (COR)', status: 'Verified' },
      { name: 'Dean’s Lister Certification', status: 'Verified' },
      { name: 'Good Moral Character', status: 'Verified' },
      { name: '2x2 ID Photo', status: 'Verified' },
    ],
    remarks: 'Partial Academic Scholarship based on 2nd Semester Dean’s List honors.'
  },
  { 
    id: '8', 
    studentId: '2023-CAPSU-0219',
    student: 'Jessica Mae E. Dela Cruz', 
    yearLevel: '3rd year', 
    course: 'BSCS', 
    courseFull: 'Bachelor of Science in Computer Science',
    category: 'Externally-Funded', 
    subType: 'CHED', 
    allocation: 'UniFast',
    gender: 'Female',
    email: 'jessicamae.delacruz@capsu.edu.ph',
    phone: '+63 927 999 1122',
    address: 'Brgy. Carida, Tapaz, Capiz',
    gwa: '1.48',
    units: 23,
    status: 'Complete',
    dateSubmitted: 'Aug 07, 2026',
    requirements: [
      { name: 'Certificate of Grades (COG)', status: 'Verified' },
      { name: 'Certificate of Registration (COR)', status: 'Verified' },
      { name: 'UniFast Masterlist Proof', status: 'Verified' },
      { name: 'Good Moral Character', status: 'Verified' },
      { name: '2x2 ID Photo', status: 'Verified' },
    ],
    remarks: 'UniFast Tertiary Education Subsidy recipient.'
  },
  { 
    id: '9', 
    studentId: '2025-CAPSU-0012',
    student: 'Mark Josh P. Lorenzo', 
    yearLevel: '1st year', 
    course: 'BSOA', 
    courseFull: 'Bachelor of Science in Office Administration',
    category: 'Externally-Funded', 
    subType: 'CHED', 
    allocation: 'TES',
    gender: 'Male',
    email: 'markjosh.lorenzo@capsu.edu.ph',
    phone: '+63 918 222 3344',
    address: 'Brgy. Daan Banwa, Tapaz, Capiz',
    gwa: '1.50',
    units: 20,
    status: 'Complete',
    dateSubmitted: 'Aug 15, 2026',
    requirements: [
      { name: 'Senior High School Report Card (Form 138)', status: 'Verified' },
      { name: 'Certificate of Registration (COR)', status: 'Verified' },
      { name: 'DSWD Listahanan Certification', status: 'Verified' },
      { name: 'Good Moral Character', status: 'Verified' },
      { name: '2x2 ID Photo', status: 'Verified' },
    ],
    remarks: 'CHED TES-1 subsidy qualified applicant.'
  },
  { 
    id: '10', 
    studentId: '2025-CAPSU-0045',
    student: 'William George I. Diaz', 
    yearLevel: '1st year', 
    course: 'BSFT', 
    courseFull: 'Bachelor of Science in Food Technology',
    category: 'Externally-Funded', 
    subType: 'Merit', 
    allocation: 'DOST',
    gender: 'Male',
    email: 'william.diaz@capsu.edu.ph',
    phone: '+63 995 444 8877',
    address: 'Brgy. Tacayan, Tapaz, Capiz',
    gwa: '1.25',
    units: 22,
    status: 'Complete',
    dateSubmitted: 'Aug 05, 2026',
    requirements: [
      { name: 'DOST-SEI Notice of Award', status: 'Verified' },
      { name: 'Certificate of Registration (COR)', status: 'Verified' },
      { name: 'High School Transcript', status: 'Verified' },
      { name: 'Good Moral Character', status: 'Verified' },
      { name: '2x2 ID Photo', status: 'Verified' },
    ],
    remarks: 'DOST Science & Technology RA 7687 Scholar.'
  },
  { 
    id: '11', 
    studentId: '2024-CAPSU-0078',
    student: 'Febe Ronile Alejandro', 
    yearLevel: '2nd year', 
    course: 'BSCS', 
    courseFull: 'Bachelor of Science in Computer Science',
    category: 'Externally-Funded', 
    subType: 'Merit', 
    allocation: 'LGU',
    gender: 'Female',
    email: 'febe.alejandro@capsu.edu.ph',
    phone: '+63 947 111 6655',
    address: 'Brgy. San Julian, Tapaz, Capiz',
    gwa: '1.58',
    units: 23,
    status: 'Complete',
    dateSubmitted: 'Aug 14, 2026',
    requirements: [
      { name: 'Certificate of Grades (COG)', status: 'Verified' },
      { name: 'Certificate of Registration (COR)', status: 'Verified' },
      { name: 'Municipal LGU Scholarship Grant Contract', status: 'Verified' },
      { name: 'Good Moral Character', status: 'Verified' },
      { name: '2x2 ID Photo', status: 'Verified' },
    ],
    remarks: 'Municipal Government of Tapaz Merit Grantee.'
  },
  { 
    id: '12', 
    studentId: '2023-CAPSU-0099',
    student: 'Ellah A. Andalecio', 
    yearLevel: '3rd year', 
    course: 'BSCS', 
    courseFull: 'Bachelor of Science in Computer Science',
    category: 'Externally-Funded', 
    subType: 'CHED', 
    allocation: 'Tulong Dunong',
    gender: 'Female',
    email: 'ellah.andalecio@capsu.edu.ph',
    phone: '+63 908 777 9900',
    address: 'Brgy. Buri, Tapaz, Capiz',
    gwa: '1.62',
    units: 23,
    status: 'Complete',
    dateSubmitted: 'Aug 12, 2026',
    requirements: [
      { name: 'Certificate of Grades (COG)', status: 'Verified' },
      { name: 'Certificate of Registration (COR)', status: 'Verified' },
      { name: 'Certificate of Indigency', status: 'Verified' },
      { name: 'Good Moral Character', status: 'Verified' },
      { name: '2x2 ID Photo', status: 'Verified' },
    ],
    remarks: 'CHED Tulong Dunong renewal scholar.'
  },
  { 
    id: '13', 
    studentId: '2022-CAPSU-0156',
    student: 'Michelle Diane C. Flores', 
    yearLevel: '4th year', 
    course: 'BSOA', 
    courseFull: 'Bachelor of Science in Office Administration',
    category: 'Externally-Funded', 
    subType: 'CHED', 
    allocation: 'Barangay (Legal dependents of Brgy. Officials)',
    gender: 'Female',
    email: 'michelle.flores@capsu.edu.ph',
    phone: '+63 930 888 2211',
    address: 'Brgy. San Roque, Tapaz, Capiz',
    gwa: '1.70',
    units: 21,
    status: 'Complete',
    dateSubmitted: 'Aug 11, 2026',
    requirements: [
      { name: 'Certificate of Grades (COG)', status: 'Verified' },
      { name: 'Certificate of Registration (COR)', status: 'Verified' },
      { name: 'DILG Barangay Official Dependent Cert', status: 'Verified' },
      { name: 'Good Moral Character', status: 'Verified' },
      { name: '2x2 ID Photo', status: 'Verified' },
    ],
    remarks: 'Statutory benefit for dependents of incumbent barangay officials under RA 7160.'
  },
  { 
    id: '14', 
    studentId: '2025-CAPSU-0067',
    student: 'Christian Jason J. Valdez', 
    yearLevel: '1st year', 
    course: 'BSFT', 
    courseFull: 'Bachelor of Science in Food Technology',
    category: 'Internally-Funded', 
    subType: 'CHED', 
    allocation: 'ESGP – PA',
    gender: 'Male',
    email: 'christian.valdez@capsu.edu.ph',
    phone: '+63 977 456 7890',
    address: 'Brgy. Wright, Tapaz, Capiz',
    gwa: '1.60',
    units: 22,
    status: 'Complete',
    dateSubmitted: 'Aug 10, 2026',
    requirements: [
      { name: 'Certificate of Grades / Form 138', status: 'Verified' },
      { name: 'Certificate of Registration (COR)', status: 'Verified' },
      { name: 'Pantawid Pamilya (4Ps) Household Cert', status: 'Verified' },
      { name: 'Good Moral Character', status: 'Verified' },
      { name: '2x2 ID Photo', status: 'Verified' },
    ],
    remarks: 'Expanded Students’ Grants-in-Aid Program for Poverty Alleviation (ESGP-PA).'
  }
];
